import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = {
    'en': {
      'title': 'RMScanner AI',
      'onboard_title_1': 'Scan Anywhere',
      'onboard_desc_1':
          'Easily scan documents on the go with high quality and auto-edge detection.',
      'onboard_title_2': 'Smart OCR',
      'onboard_desc_2':
          'Extract text from your scanned documents in multiple languages instantly.',
      'onboard_title_3': 'Organize & Share',
      'onboard_desc_3':
          'Convert scans to PDF, organize files, and share them securely.',
      'skip': 'SKIP',
      'start': 'START',
      'home': 'Home',
      'files': 'Files',
      'tools': 'Tools',
      'ocr': 'OCR',
      'profile': 'Profile',
      'scan_doc': 'Scan Document',
      'scan_subtitle': 'Capture receipts, notes, and IDs',
      'quick_actions': 'Quick Actions',
      'recent_files': 'Recent Files',
      'see_all': 'See All',
      'see_all_tools': 'See All Tools',
      'image_to_pdf': 'Image to PDF',
      'image_to_text': 'Image to Text',
      'pdf_to_text': 'PDF to Text',
      'pdf_to_image': 'PDF to Image',
      'text_to_pdf': 'Text to PDF',
      'settings': 'Settings',
      'basic': 'Basic',
      'scan': 'Scan',
      'pdf_ocr_section': 'PDF & OCR',
      'data': 'Data',
      'theme': 'Theme',
      'language': 'Language',
      'auto_enhance': 'Auto Enhance',
      'scan_quality': 'Scan Quality',
      'default_page_size': 'Default Page Size',
      'ocr_language': 'OCR Language',
      'clear_cache': 'Clear Cache',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'upgrade_title': 'Free User',
      'upgrade_subtitle': 'Upgrade to Unlock All Features',
      'upgrade_button': 'Upgrade',
      'refer_friend': 'Refer a Friend',
      'scan_section': 'Scan Preferences',
      'support_privacy': 'Support & Privacy',
      'privacy_policy': 'Privacy Policy',
      'feature_request': 'Feature Request',
      'report_bug': 'Report a Bug',
      'support_developer': 'Support Developer',
      'loading_support_ad': 'Loading ad...',
      'thank_you_support': 'Thank you for your support!',
      'ad_not_ready': 'Ad is not ready yet. Please try again later.',
      'data_section': 'Data Management',
      'use_system_font': 'System Font',
      'system_font': 'System',
      'app_font': 'App Font (SamsungOne)',
      'saved_to_downloads': 'Saved to Downloads folder',
      'could_not_save_permission':
          'Could not save: Please allow storage permission.',
      'could_not_open_file': 'Could not open the file.',
      'error_opening_file': 'An error occurred while opening the file.',
      'scan_error': 'An error occurred during scanning. Please try again.',
      'pdf_created_successfully': 'PDF Created Successfully',
      'image_to_pdf_success': 'Image to PDF Created Successfully',
      'pdfs_merged_success': 'PDFs Merged Successfully',
      'pdf_split_success': 'PDF Split Successfully',
      'pdf_compressed_success': 'PDF Compressed Successfully',
      'pdf_rotated_success': 'PDF Rotated Successfully',
      'pdf_locked_success': 'PDF Locked Successfully',
      'pdf_unlocked_success': 'PDF Unlocked Successfully',
      'incorrect_password': 'Incorrect password. Please try again.',
      'failed_to_unlock': 'Failed to unlock PDF. Please try again.',
      'pdf_to_image_success': 'PDF to Image Successful',
      'pdf_to_text_success': 'PDF to Text Successful',
      'signature_saved': 'Signature saved successfully',
      'text_to_pdf_error': 'Failed to convert text to PDF. Please try again.',
      'error_prefix': 'An unexpected error occurred. Please try again.',
      'pdf_saved_successfully': 'PDF saved successfully',
      'document_saved_successfully': 'Document saved successfully',
      'error_saving_doc':
          'Failed to save the document. Please check storage permissions.',
      'error_sharing': 'Could not share the document. Please try again.',
      'text_copied': 'Text copied to clipboard',
      'saved_success_text': 'Saved successfully as text file.',
      'error_picking_image': 'Could not pick the image. Please try again.',
      'error_picking_pdf': 'Could not open the PDF. Please try again.',
      'error_capturing_image':
          'Could not capture photo. Please check your camera.',
      'cache_cleared': 'Cache cleared',
      'images_saved': 'image(s) saved successfully',
      'invalid_page_range': 'Invalid page range entered',
      'already_protected': 'This PDF is already password protected.',
      'not_protected': 'This PDF is not password protected.',
      'could_not_open_privacy_policy': 'Could not open Privacy Policy',
      'could_not_open_email': 'Could not open Email app',
      'deleted_successfully': '\$fileType deleted successfully',
      'no_text_in_pdf': 'No text found in PDF',
      'no_text_in_image': 'No text found in image',
      'clear': 'Clear',
      'menu': 'Menu',
      'about': 'About',
      'about_description': 'RMScanner AI is a free, all-in-one document scanner app with OCR, PDF tools, and QR scanner. Scan, convert, and share your documents anytime, anywhere.',
      'app_version': 'Version',
      'developed_by': 'Developed by',
      'features': 'Features',
      'contact_support': 'Contact Support',
      'convert_photos': 'Convert photos',
      'extract_ocr': 'Extract (OCR)',
      'convert_pdf': 'Convert PDF',
      'create_doc': 'Create Doc',
      'no_recent_files': 'No recent files',
      'sort_by': 'Sort By',
      'sort_date': 'Date (Newest First)',
      'sort_name': 'Name (A-Z)',
      'sort_size': 'Size (Largest First)',
      'search_hint': 'Search documents, PDFs...',
      'tab_recent': 'Recent',
      'tab_pdfs': 'PDFs',
      'tab_images': 'Images',
      'tab_ocr_text': 'OCR Text',
      'no_files_found': 'No files found',
      'just_now': 'Just now',
      'min_ago': 'min ago',
      'hours_ago': 'hours ago',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'all_tools': 'All Tools',
      'pdf_tools': 'PDF Tools',
      'converters': 'Converters',
      'privacy_security': 'Privacy & Security',
      'merge_pdf': 'Merge PDF',
      'split_pdf': 'Split PDF',
      'compress_pdf': 'Compress PDF',
      'rotate_pdf': 'Rotate PDF',
      'high_quality': 'HIGH QUALITY',
      'fast_scan': 'FAST SCAN',
      'easy_edit': 'EASY EDIT',
      'extract_data': 'EXTRACT DATA',
      'lock_pdf': 'Lock PDF',
      'add_password_protection': 'Add password protection',
      'unlock_pdf': 'Unlock PDF',
      'remove_restrictions': 'Remove document restrictions',
      'add_signature': 'Add Signature',
      'digitally_sign': 'Digitally sign documents',
      'select_ocr_language': 'Select OCR Language',
      'extract_text_title': 'Extract Text with AI',
      'extract_text_subtitle': 'Select a source to begin extracting text from your documents.',
      'source_image': 'Image',
      'source_pdf': 'PDF',
      'source_camera': 'Camera',
      'capture_document': 'Capture Document',
      'select_file': 'Select File',
      'extracting_from_image': 'Extracting text from image...',
      'extracting_from_pdf': 'Extracting text from PDF...',
      'extracting_from_capture': 'Extracting text from capture...',
      'text_extracted_success': 'Text extracted successfully!',
      'extraction_results': 'Extraction Results',
      'copy': 'Copy',
      'document_statistics': 'Document Statistics',
      'words': 'words',
      'characters': 'characters',
      'extracted_text': 'Extracted Text',
      'no_text_hint': 'No text extracted. Try editing here...',
      'save_document': 'Save Document',
      'save': 'Save',
      'share': 'Share',
      'scan_result': 'Scan Result',
      'failed_to_load_image': 'Failed to load image',
      'pages_scanned_format': 'scanned  •  Choose save format',
      'save_as': 'Save As',
      'document': 'Document',
      'share_scanned_pages': 'Share Scanned Pages',
      'saving': 'Saving...',
      'open_settings': 'Open Settings',
      'camera_permission_msg': 'Camera permission is required to scan.',
      'permission_required': '\$name Permission Required',
      'creating_pdf': 'Creating PDF...',
      'delete_confirm': 'Delete',
      'file_options': 'File Options',
      'rename': 'Rename',
      'download': 'Download',
      'delete_confirmation': 'Are you sure you want to delete "\$fileName"? This action cannot be undone.',
      'watermark_pdf': 'Watermark PDF',
      'add_text_watermark': 'Add text watermark to PDF',
      'watermark_text': 'Watermark Text',
      'watermark_text_hint': 'Enter watermark text...',
      'watermark_opacity': 'Opacity',
      'watermark_font_size': 'Font Size',
      'watermark_bold': 'Bold',
      'watermark_italic': 'Italic',
      'watermark_tiled': 'Tiled (Repeat Pattern)',
      'watermark_font': 'Font Family',
      'watermark_rotation': 'Rotation',
      'watermark_success': 'Watermark added successfully',
      'watermark_error': 'Failed to add watermark',
      'watermark_text_empty': 'Please enter watermark text',
      'reorder_pages': 'Arrange PDF Pages',
      'reorder_delete_pages': 'Reorder or delete PDF pages',
      'delete_page': 'Delete',
      'move_up': 'Move Up',
      'move_down': 'Move Down',
      'page': 'Page',
      'reorder_success': 'Pages reordered successfully',
      'reorder_error': 'Failed to reorder pages',
      'no_pages_to_show': 'No pages to display',
      'qr_scanner': 'QR Scanner',
      'scan_qr_barcode': 'Scan QR & Barcode',
      'qr_code_detected': 'Code Detected',
      'qr_result': 'Scan Result',
      'qr_save_as_text': 'Save as Text',
      'qr_save_as_image': 'Save as Image',
      'qr_open_url': 'Open URL',
      'qr_copy_text': 'Copy Text',
      'qr_no_code_detected': 'No code detected yet',
      'qr_point_at_code': 'Point your camera at a QR code or barcode',
      'qr_saved_success': 'QR code saved successfully',
      'qr_invalid_url': 'Invalid URL',
      'qr_scan_again': 'Scan Again',
      'qr_copied_to_clipboard': 'Copied to clipboard',
      'close': 'Close',
      'batch_ocr': 'Batch OCR',
      'batch_ocr_subtitle': 'Extract text from multiple images',
      'batch_ocr_select_images': 'Select Multiple Images',
      'batch_ocr_processing': 'Processing image',
      'batch_ocr_of': 'of',
      'batch_ocr_export_txt': 'Export as TXT',
      'batch_ocr_export_csv': 'Export as CSV',
      'batch_ocr_error': 'Batch OCR failed',
      'batch_ocr_no_text': 'No text found in any image',
      'batch_ocr_select_source': 'Choose image source for Batch OCR',
      'batch_ocr_from_gallery': 'From Gallery',
      'batch_ocr_from_camera': 'From Camera',
      'batch_ocr_captured_count': '\$count image(s) captured. Capture more?',
      'batch_ocr_capture_more': 'Capture More',
      'batch_ocr_done': 'Done',
      'batch_ocr_results': 'Batch OCR Results',
      'export_format': 'Export Format',
      'ai_prompt': 'AI Prompt',
      'generate_ai_prompt': 'Generate AI Prompt',
      'ai_prompt_guide': 'How to Use with AI',
      'ai_prompt_guide_step1': '1. Copy or share the generated prompt',
      'ai_prompt_guide_step2': '2. Open your favorite AI app (ChatGPT, Gemini, Claude, etc.)',
      'ai_prompt_guide_step3': '3. Paste the prompt and send it to the AI',
      'prompt_summarize': 'Summarize',
      'prompt_qa': 'Q&A',
      'prompt_translate': 'Translate',
      'prompt_extract_data': 'Extract Data',
      'prompt_summarize_desc': 'Get a concise summary of the document',
      'prompt_qa_desc': 'Ask questions about the document',
      'prompt_translate_desc': 'Translate the document to English',
      'prompt_extract_data_desc': 'Extract names, dates, amounts, and key info',
      'prompt_copied': 'Prompt copied to clipboard',
      'copy_prompt': 'Copy Prompt',
      'share_prompt': 'Share Prompt',
      'ai_guide_title': 'AI Assistant Guide',
      'ai_guide_desc': 'Use the generated prompt with your favorite AI tool',
      'open_chatgpt': 'Open ChatGPT',
      'open_gemini': 'Open Gemini',
      'open_claude': 'Open Claude',
      'open_copilot': 'Open Copilot',
      'open_deepseek': 'Open DeepSeek',
      'prompt_preview': 'Prompt Preview',
      'select_template': 'Select a Template',
      'ai_tools': 'AI Tools',
      'processing': 'Processing...',
      'may_take_a_while': 'This may take a while for large files.',
      'notify_when_ready': 'Notify When Ready',
      'save_as_copy': 'Save as Copy',
      'watermark_preview': 'Preview',
      'watermark_apply': 'Apply Watermark',
      'open_perplexity': 'Open Perplexity',
      'open_mistral': 'Open Mistral',
      'open_grok': 'Open Grok',
      'open_meta_ai': 'Open Meta AI',
      'open_you_com': 'Open You.com',
      'open_pi': 'Open Pi',
      'open_ai_failed': 'Could not open AI app. Please try again.',
      'draw_signature': 'Draw Signature',
      'please_sign': 'Please sign inside the white box below.',
      'undo': 'Undo',
      'page_of': 'Page \$current of \$total',
      'drag_scale_signature': 'Drag & Scale Signature',
      'confirm_save_stamp': 'Confirm & Save Stamp',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'quality_low': 'Low',
      'quality_medium': 'Medium',
      'quality_high': 'High',
      'quality_ultra': 'Ultra',
      'clear_cache_confirm': 'This will delete all cached files (\$size). Continue?',
      'batch_ocr_success': 'Batch OCR Successful',
    },
    'id': {
      'title': 'RMScanner AI',
      'onboard_title_1': 'Pindai Di Mana Saja',
      'onboard_desc_1':
          'Pindai dokumen dengan mudah di mana saja dengan kualitas tinggi dan deteksi tepi otomatis.',
      'onboard_title_2': 'OCR Pintar',
      'onboard_desc_2':
          'Ekstrak teks dari dokumen yang dipindai dalam berbagai bahasa secara instan.',
      'onboard_title_3': 'Atur & Bagikan',
      'onboard_desc_3':
          'Ubah pindaian menjadi PDF, atur file, dan bagikan dengan aman.',
      'skip': 'LEWATI',
      'start': 'MULAI',
      'home': 'Beranda',
      'files': 'Berkas',
      'tools': 'Alat',
      'ocr': 'OCR',
      'profile': 'Profil',
      'scan_doc': 'Pindai Dokumen',
      'scan_subtitle': 'Pindai struk, catatan, dan KTP',
      'quick_actions': 'Aksi Cepat',
      'recent_files': 'Berkas Terbaru',
      'see_all': 'Lihat Semua',
      'see_all_tools': 'Lihat Semua Alat',
      'image_to_pdf': 'Gambar ke PDF',
      'image_to_text': 'Gambar ke Teks',
      'pdf_to_text': 'PDF ke Teks',
      'pdf_to_image': 'PDF ke Gambar',
      'text_to_pdf': 'Teks ke PDF',
      'settings': 'Pengaturan',
      'basic': 'Dasar',
      'scan': 'Pindai',
      'pdf_ocr_section': 'PDF & OCR',
      'data': 'Data',
      'theme': 'Tema',
      'language': 'Bahasa',
      'auto_enhance': 'Tingkatkan Otomatis',
      'scan_quality': 'Kualitas Pindai',
      'default_page_size': 'Ukuran Halaman',
      'ocr_language': 'Bahasa OCR',
      'clear_cache': 'Hapus Cache',
      'confirm': 'Konfirmasi',
      'cancel': 'Batal',
      'upgrade_title': 'Pengguna Gratis',
      'upgrade_subtitle': 'Upgrade untuk Buka Semua Fitur',
      'upgrade_button': 'Upgrade',
      'refer_friend': 'Ajak Teman',
      'scan_section': 'Preferensi Pindai',
      'support_privacy': 'Dukungan & Privasi',
      'privacy_policy': 'Kebijakan Privasi',
      'feature_request': 'Minta Fitur',
      'report_bug': 'Laporkan Bug',
      'support_developer': 'Dukung Developer',
      'loading_support_ad': 'Memuat iklan...',
      'thank_you_support': 'Terima kasih atas dukungan Anda!',
      'ad_not_ready': 'Iklan belum siap. Silakan coba lagi nanti.',
      'data_section': 'Manajemen Data',
      'use_system_font': 'Font Sistem',
      'system_font': 'Sistem',
      'app_font': 'Font Aplikasi (SamsungOne)',
      'saved_to_downloads': 'Tersimpan di folder Downloads',
      'could_not_save_permission':
          'Tidak bisa menyimpan: Mohon izinkan akses penyimpanan.',
      'could_not_open_file': 'Tidak dapat membuka berkas.',
      'error_opening_file': 'Terjadi kesalahan saat membuka berkas.',
      'scan_error': 'Terjadi kesalahan saat memindai. Silakan coba lagi.',
      'pdf_created_successfully': 'PDF berhasil dibuat',
      'image_to_pdf_success': 'Gambar ke PDF berhasil dibuat',
      'pdfs_merged_success': 'PDF berhasil digabungkan',
      'pdf_split_success': 'PDF berhasil dipisah',
      'pdf_compressed_success': 'PDF berhasil dikompres',
      'pdf_rotated_success': 'PDF berhasil diputar',
      'pdf_locked_success': 'PDF berhasil dikunci',
      'pdf_unlocked_success': 'PDF berhasil dibuka kunci',
      'incorrect_password': 'Kata sandi salah. Silakan coba lagi.',
      'failed_to_unlock': 'Gagal membuka kunci PDF. Silakan coba lagi.',
      'pdf_to_image_success': 'PDF ke Gambar berhasil',
      'pdf_to_text_success': 'PDF ke Teks berhasil',
      'signature_saved': 'Tanda tangan berhasil disimpan',
      'text_to_pdf_error': 'Gagal mengubah teks ke PDF. Silakan coba lagi.',
      'error_prefix': 'Terjadi kesalahan tak terduga. Silakan coba lagi.',
      'pdf_saved_successfully': 'PDF berhasil disimpan',
      'document_saved_successfully': 'Dokumen berhasil disimpan',
      'error_saving_doc': 'Gagal menyimpan dokumen. Periksa izin penyimpanan.',
      'error_sharing': 'Tidak dapat membagikan dokumen. Silakan coba lagi.',
      'text_copied': 'Teks disalin ke papan klip',
      'saved_success_text': 'Berhasil disimpan sebagai berkas teks.',
      'error_picking_image': 'Tidak dapat memilih gambar. Silakan coba lagi.',
      'error_picking_pdf': 'Tidak dapat membuka PDF. Silakan coba lagi.',
      'error_capturing_image':
          'Tidak dapat mengambil foto. Periksa kamera Anda.',
      'cache_cleared': 'Cache dibersihkan',
      'images_saved': 'gambar berhasil disimpan',
      'invalid_page_range': 'Rentang halaman tidak valid',
      'already_protected': 'PDF ini sudah dilindungi kata sandi.',
      'not_protected': 'PDF ini tidak dilindungi kata sandi.',
      'could_not_open_privacy_policy': 'Tidak dapat membuka Kebijakan Privasi',
      'could_not_open_email': 'Tidak dapat membuka aplikasi Email',
      'deleted_successfully': '\$fileType berhasil dihapus',
      'no_text_in_pdf': 'Tidak ada teks ditemukan dalam PDF',
      'no_text_in_image': 'Tidak ada teks ditemukan dalam gambar',
      'clear': 'Hapus',
      'menu': 'Menu',
      'about': 'Tentang',
      'about_description': 'RMScanner AI adalah aplikasi pemindai dokumen serbaguna yang gratis dengan OCR, alat PDF, dan pemindai QR. Pindai, konversi, dan bagikan dokumen Anda kapan saja, di mana saja.',
      'app_version': 'Versi',
      'developed_by': 'Dikembangkan oleh',
      'features': 'Fitur',
      'contact_support': 'Hubungi Dukungan',
      'convert_photos': 'Konversi foto',
      'extract_ocr': 'Ekstrak (OCR)',
      'convert_pdf': 'Konversi PDF',
      'create_doc': 'Buat Dok',
      'no_recent_files': 'Tidak ada file terbaru',
      'sort_by': 'Urutkan',
      'sort_date': 'Tanggal (Terbaru)',
      'sort_name': 'Nama (A-Z)',
      'sort_size': 'Ukuran (Terbesar)',
      'search_hint': 'Cari dokumen, PDF...',
      'tab_recent': 'Terbaru',
      'tab_pdfs': 'PDF',
      'tab_images': 'Gambar',
      'tab_ocr_text': 'Teks OCR',
      'no_files_found': 'Tidak ada file ditemukan',
      'just_now': 'Baru saja',
      'min_ago': 'menit lalu',
      'hours_ago': 'jam lalu',
      'yesterday': 'Kemarin',
      'days_ago': 'hari lalu',
      'all_tools': 'Semua Alat',
      'pdf_tools': 'Alat PDF',
      'converters': 'Konverter',
      'privacy_security': 'Privasi & Keamanan',
      'merge_pdf': 'Gabung PDF',
      'split_pdf': 'Pisah PDF',
      'compress_pdf': 'Kompres PDF',
      'rotate_pdf': 'Putar PDF',
      'high_quality': 'KUALITAS TINGGI',
      'fast_scan': 'SCAN CEPAT',
      'easy_edit': 'EDIT MUDAH',
      'extract_data': 'EKSTRAK DATA',
      'lock_pdf': 'Kunci PDF',
      'add_password_protection': 'Tambahkan proteksi kata sandi',
      'unlock_pdf': 'Buka PDF',
      'remove_restrictions': 'Hapus batasan dokumen',
      'add_signature': 'Tambah Tanda Tangan',
      'digitally_sign': 'Tanda tangan digital dokumen',
      'select_ocr_language': 'Pilih Bahasa OCR',
      'extract_text_title': 'Ekstrak Teks dengan AI',
      'extract_text_subtitle': 'Pilih sumber untuk mulai mengekstrak teks dari dokumen Anda.',
      'source_image': 'Gambar',
      'source_pdf': 'PDF',
      'source_camera': 'Kamera',
      'capture_document': 'Ambil Dokumen',
      'select_file': 'Pilih File',
      'extracting_from_image': 'Mengekstrak teks dari gambar...',
      'extracting_from_pdf': 'Mengekstrak teks dari PDF...',
      'extracting_from_capture': 'Mengekstrak teks dari tangkapan...',
      'text_extracted_success': 'Teks berhasil diekstrak!',
      'extraction_results': 'Hasil Ekstraksi',
      'copy': 'Salin',
      'document_statistics': 'Statistik Dokumen',
      'words': 'kata',
      'characters': 'karakter',
      'extracted_text': 'Teks yang Diekstrak',
      'no_text_hint': 'Tidak ada teks diekstrak. Coba edit di sini...',
      'save_document': 'Simpan Dokumen',
      'save': 'Simpan',
      'share': 'Bagikan',
      'scan_result': 'Hasil Pindai',
      'failed_to_load_image': 'Gagal memuat gambar',
      'pages_scanned_format': 'dipindai  •  Pilih format simpan',
      'save_as': 'Simpan Sebagai',
      'document': 'Dokumen',
      'share_scanned_pages': 'Bagikan Halaman Pindai',
      'saving': 'Menyimpan...',
      'open_settings': 'Buka Pengaturan',
      'camera_permission_msg': 'Izin kamera diperlukan untuk memindai.',
      'permission_required': 'Izin \$name Diperlukan',
      'creating_pdf': 'Membuat PDF...',
      'delete_confirm': 'Hapus',
      'file_options': 'Opsi File',
      'rename': 'Ganti Nama',
      'download': 'Unduh',
      'delete_confirmation': 'Apakah Anda yakin ingin menghapus "\$fileName"? Tindakan ini tidak dapat dibatalkan.',
      'watermark_pdf': 'Watermark PDF',
      'add_text_watermark': 'Tambah teks watermark ke PDF',
      'watermark_text': 'Teks Watermark',
      'watermark_text_hint': 'Masukkan teks watermark...',
      'watermark_opacity': 'Opasitas',
      'watermark_font_size': 'Ukuran Font',
      'watermark_bold': 'Tebal',
      'watermark_italic': 'Miring',
      'watermark_tiled': 'Ubin (Pola Berulang)',
      'watermark_font': 'Jenis Font',
      'watermark_rotation': 'Rotasi',
      'watermark_success': 'Watermark berhasil ditambahkan',
      'watermark_error': 'Gagal menambahkan watermark',
      'watermark_text_empty': 'Silakan masukkan teks watermark',
      'reorder_pages': 'Atur Halaman PDF',
      'reorder_delete_pages': 'Atur ulang atau hapus halaman PDF',
      'delete_page': 'Hapus',
      'move_up': 'Naik',
      'move_down': 'Turun',
      'page': 'Halaman',
      'reorder_success': 'Halaman berhasil diatur ulang',
      'reorder_error': 'Gagal mengatur ulang halaman',
      'no_pages_to_show': 'Tidak ada halaman untuk ditampilkan',
      'qr_scanner': 'Pemindai QR',
      'scan_qr_barcode': 'Pindai QR & Barcode',
      'qr_code_detected': 'Kode Terdeteksi',
      'qr_result': 'Hasil Pindai',
      'qr_save_as_text': 'Simpan sebagai Teks',
      'qr_save_as_image': 'Simpan sebagai Gambar',
      'qr_open_url': 'Buka URL',
      'qr_copy_text': 'Salin Teks',
      'qr_no_code_detected': 'Belum ada kode terdeteksi',
      'qr_point_at_code': 'Arahkan kamera ke kode QR atau barcode',
      'qr_saved_success': 'Kode QR berhasil disimpan',
      'qr_invalid_url': 'URL tidak valid',
      'qr_scan_again': 'Pindai Lagi',
      'qr_copied_to_clipboard': 'Disalin ke papan klip',
      'close': 'Tutup',
      'batch_ocr': 'OCR Massal',
      'batch_ocr_subtitle': 'Ekstrak teks dari banyak gambar',
      'batch_ocr_select_images': 'Pilih Banyak Gambar',
      'batch_ocr_processing': 'Memproses gambar',
      'batch_ocr_of': 'dari',
      'batch_ocr_export_txt': 'Ekspor sebagai TXT',
      'batch_ocr_export_csv': 'Ekspor sebagai CSV',
      'batch_ocr_success': 'OCR Massal Berhasil',
      'batch_ocr_error': 'OCR massal gagal',
      'batch_ocr_no_text': 'Tidak ada teks ditemukan di gambar mana pun',
      'batch_ocr_select_source': 'Pilih sumber gambar untuk OCR Massal',
      'batch_ocr_from_gallery': 'Dari Galeri',
      'batch_ocr_from_camera': 'Dari Kamera',
      'batch_ocr_captured_count': '\$count gambar diambil. Ambil lagi?',
      'batch_ocr_capture_more': 'Ambil Lagi',
      'batch_ocr_done': 'Selesai',
      'batch_ocr_results': 'Hasil OCR Massal',
      'export_format': 'Format Ekspor',
      'ai_prompt': 'Prompt AI',
      'generate_ai_prompt': 'Hasilkan Prompt AI',
      'ai_prompt_guide': 'Cara Menggunakan dengan AI',
      'ai_prompt_guide_step1': '1. Salin atau bagikan prompt yang dihasilkan',
      'ai_prompt_guide_step2': '2. Buka aplikasi AI favorit Anda (ChatGPT, Gemini, Claude, dll)',
      'ai_prompt_guide_step3': '3. Tempel prompt dan kirim ke AI',
      'prompt_summarize': 'Ringkas',
      'prompt_qa': 'Tanya Jawab',
      'prompt_translate': 'Terjemahkan',
      'prompt_extract_data': 'Ekstrak Data',
      'prompt_summarize_desc': 'Dapatkan ringkasan singkat dokumen',
      'prompt_qa_desc': 'Ajukan pertanyaan tentang dokumen',
      'prompt_translate_desc': 'Terjemahkan dokumen ke Bahasa Inggris',
      'prompt_extract_data_desc': 'Ekstrak nama, tanggal, jumlah, dan info penting',
      'prompt_copied': 'Prompt disalin ke papan klip',
      'copy_prompt': 'Salin Prompt',
      'share_prompt': 'Bagikan Prompt',
      'ai_guide_title': 'Panduan Asisten AI',
      'ai_guide_desc': 'Gunakan prompt yang dihasilkan dengan alat AI favorit Anda',
      'open_chatgpt': 'Buka ChatGPT',
      'open_gemini': 'Buka Gemini',
      'open_claude': 'Buka Claude',
      'open_copilot': 'Buka Copilot',
      'open_deepseek': 'Buka DeepSeek',
      'prompt_preview': 'Pratinjau Prompt',
      'select_template': 'Pilih Template',
      'ai_tools': 'Alat AI',
      'processing': 'Memproses...',
      'may_take_a_while': 'Ini mungkin memakan waktu untuk file besar.',
      'notify_when_ready': 'Beritahu Saat Selesai',
      'save_as_copy': 'Simpan sebagai Salinan',
      'watermark_preview': 'Pratinjau',
      'watermark_apply': 'Terapkan Watermark',
      'open_perplexity': 'Buka Perplexity',
      'open_mistral': 'Buka Mistral',
      'open_grok': 'Buka Grok',
      'open_meta_ai': 'Buka Meta AI',
      'open_you_com': 'Buka You.com',
      'open_pi': 'Buka Pi',
      'open_ai_failed': 'Tidak dapat membuka aplikasi AI. Silakan coba lagi.',
      'draw_signature': 'Buat Tanda Tangan',
      'please_sign': 'Silakan tanda tangan di dalam kotak putih di bawah.',
      'undo': 'Urungkan',
      'page_of': 'Halaman \$current dari \$total',
      'drag_scale_signature': 'Seret & Skala Tanda Tangan',
      'confirm_save_stamp': 'Konfirmasi & Simpan Stempel',
      'theme_light': 'Terang',
      'theme_dark': 'Gelap',
      'theme_system': 'Sistem',
      'quality_low': 'Rendah',
      'quality_medium': 'Sedang',
      'quality_high': 'Tinggi',
      'quality_ultra': 'Ultra',
      'clear_cache_confirm': 'Ini akan menghapus semua file cache (\$size). Lanjutkan?',
    },
    'bn': {
      'title': 'আরএম-স্ক্যানার এআই',
      'onboard_title_1': 'যেকোনো জায়গায় স্ক্যান করুন',
      'onboard_desc_1':
          'উচ্চ মানের এবং স্বয়ংক্রিয় প্রান্ত সনাক্তকরণের সাথে যেকোনো জায়গায় সহজে ডকুমেন্ট স্ক্যান করুন।',
      'onboard_title_2': 'স্মার্ট OCR',
      'onboard_desc_2':
          'একাধিক ভাষায় আপনার স্ক্যান করা ডকুমেন্ট থেকে তাৎক্ষণিকভাবে টেক্সট বের করুন।',
      'onboard_title_3': 'সংগঠিত করুন ও শেয়ার করুন',
      'onboard_desc_3':
          'স্ক্যানগুলি PDF-এ রূপান্তর করুন, ফাইল সংগঠিত করুন এবং নিরাপদে শেয়ার করুন।',
      'skip': 'এড়িয়ে যান',
      'start': 'শুরু',
      'home': 'হোম',
      'files': 'ফাইল',
      'tools': 'টুলস',
      'ocr': 'ওসিআর',
      'profile': 'প্রোফাইল',
      'scan_doc': 'ডকুমেন্ট স্ক্যান',
      'scan_subtitle': 'রসিদ, নোট এবং আইডি সংরক্ষণ করুন',
      'quick_actions': 'দ্রুত কাজ',
      'recent_files': 'সাম্প্রতিক ফাইল',
      'see_all': 'সব দেখুন',
      'see_all_tools': 'সব টুল দেখুন',
      'image_to_pdf': 'ছবি থেকে পিডিএফ',
      'image_to_text': 'ছবি থেকে লেখা',
      'pdf_to_text': 'পিডিএফ থেকে লেখা',
      'pdf_to_image': 'পিডিএফ থেকে ছবি',
      'text_to_pdf': 'লেখা থেকে পিডিএফ',
      'settings': 'সেটিংস',
      'basic': 'মৌলিক',
      'scan': 'স্ক্যান',
      'pdf_ocr_section': 'পিডিএফ ও ওসিআর',
      'data': 'ডেটা',
      'theme': 'থিম',
      'language': 'ভাষা',
      'auto_enhance': 'অটো এনহ্যান্স',
      'scan_quality': 'স্ক্যান কোয়ালিটি',
      'default_page_size': 'পেজ সাইজ',
      'ocr_language': 'ওসিআর ভাষা',
      'clear_cache': 'ক্যাশ মুছুন',
      'confirm': 'নিশ্চিত করুন',
      'cancel': 'বাতিল করুন',
      'upgrade_title': 'ফ্রি ইউজার',
      'upgrade_subtitle': 'সব ফিচার আনলক করতে আপগ্রেড করুন',
      'upgrade_button': 'আপগ্রেড',
      'refer_friend': 'বন্ধুকে রেফার করুন',
      'scan_section': 'স্ক্যান প্রিফারেন্স',
      'support_privacy': 'সাপোর্ট এবং গোপনীয়তা',
      'privacy_policy': 'প্রাইভেসি পলিসি',
      'feature_request': 'ফিচার রিকোয়েস্ট',
      'report_bug': 'বাগ রিপোর্ট',
      'support_developer': 'ডেভেলপারকে সাপোর্ট করুন',
      'loading_support_ad': 'বিজ্ঞাপন লোড হচ্ছে...',
      'thank_you_support': 'আপনার সমর্থনের জন্য ধন্যবাদ!',
      'ad_not_ready': 'বিজ্ঞাপন এখনো তৈরি নয়। পরে আবার চেষ্টা করুন।',
      'data_section': 'ডেটা ম্যানেজমেন্ট',
      'use_system_font': 'সিস্টেম ফন্ট',
      'system_font': 'সিস্টেম',
      'app_font': 'অ্যাপ ফন্ট (SamsungOne)',
      'saved_to_downloads': 'ডাউনলোড ফোল্ডারে সংরক্ষিত হয়েছে',
      'could_not_save_permission': 'সংরক্ষণ করা যায়নি: স্টোরেজ অনুমতি দিন।',
      'could_not_open_file': 'ফাইল খোলা যায়নি।',
      'error_opening_file': 'ফাইল খোলার সময় ত্রুটি ঘটেছে।',
      'scan_error': 'স্ক্যানিং সময় ত্রুটি ঘটেছে। আবার চেষ্টা করুন।',
      'pdf_created_successfully': 'PDF সফলভাবে তৈরি হয়েছে',
      'image_to_pdf_success': 'ছবি থেকে PDF সফলভাবে তৈরি হয়েছে',
      'pdfs_merged_success': 'PDF সফলভাবে একত্রিত হয়েছে',
      'pdf_split_success': 'PDF সফলভাবে বিভক্ত হয়েছে',
      'pdf_compressed_success': 'PDF সফলভাবে কম্প্রেস করা হয়েছে',
      'pdf_rotated_success': 'PDF সফলভাবে ঘূর্ণন করা হয়েছে',
      'pdf_locked_success': 'PDF সফলভাবে লক করা হয়েছে',
      'pdf_unlocked_success': 'PDF সফলভাবে আনলক করা হয়েছে',
      'incorrect_password': 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।',
      'failed_to_unlock': 'PDF আনলক করতে ব্যর্থ। আবার চেষ্টা করুন।',
      'pdf_to_image_success': 'PDF থেকে ছবি সফল',
      'pdf_to_text_success': 'PDF থেকে টেক্সট সফল',
      'signature_saved': 'স্বাক্ষর সফলভাবে সংরক্ষিত হয়েছে',
      'text_to_pdf_error': 'টেক্সট থেকে PDF রূপান্তর ব্যর্থ। আবার চেষ্টা করুন।',
      'error_prefix': 'একটি অপ্রত্যাশিত ত্রুটি ঘটেছে। আবার চেষ্টা করুন।',
      'pdf_saved_successfully': 'PDF সফলভাবে সংরক্ষিত হয়েছে',
      'document_saved_successfully': 'ডকুমেন্ট সফলভাবে সংরক্ষিত হয়েছে',
      'error_saving_doc': 'ডকুমেন্ট সংরক্ষণ ব্যর্থ। স্টোরেজ অনুমতি যাচাই করুন।',
      'error_sharing': 'ডকুমেন্ট শেয়ার করা যায়নি। আবার চেষ্টা করুন।',
      'text_copied': 'টেক্সট ক্লিপবোর্ডে কপি হয়েছে',
      'saved_success_text': 'টেক্সট ফাইল হিসেবে সফলভাবে সংরক্ষিত হয়েছে।',
      'error_picking_image': 'ছবি নির্বাচন করা যায়নি। আবার চেষ্টা করুন।',
      'error_picking_pdf': 'PDF খোলা যায়নি। আবার চেষ্টা করুন।',
      'error_capturing_image': 'ছবি তোলা যায়নি। ক্যামেরা যাচাই করুন।',
      'cache_cleared': 'ক্যাশ পরিষ্কার করা হয়েছে',
      'images_saved': 'ছবি সফলভাবে সংরক্ষিত হয়েছে',
      'invalid_page_range': 'অবৈধ পৃষ্ঠা রেঞ্জ',
      'already_protected': 'এই PDF ইতিমধ্যে পাসওয়ার্ড সুরক্ষিত।',
      'not_protected': 'এই PDF পাসওয়ার্ড সুরক্ষিত নয়।',
      'could_not_open_privacy_policy': 'প্রাইভেসি পলিসি খোলা যায়নি',
      'could_not_open_email': 'ইমেল অ্যাপ খোলা যায়নি',
      'deleted_successfully': '\$fileType সফলভাবে মুছে ফেলা হয়েছে',
      'no_text_in_pdf': 'PDF-এ কোনো টেক্সট পাওয়া যায়নি',
      'no_text_in_image': 'ছবিতে কোনো টেক্সট পাওয়া যায়নি',
      'clear': 'মুছুন',
      'menu': 'মেনু',
      'about': 'সম্পর্কে',
      'about_description': 'RMScanner AI একটি বিনামূল্যের সর্ব-ইন-ওয়ান ডকুমেন্ট স্ক্যানার অ্যাপ যাতে OCR, PDF টুল এবং QR স্ক্যানার রয়েছে। যেকোনো সময়, যেকোনো জায়গায় আপনার ডকুমেন্ট স্ক্যান করুন, রূপান্তর করুন এবং শেয়ার করুন।',
      'app_version': 'ভার্সন',
      'developed_by': 'দ্বারা উন্নত',
      'features': 'বৈশিষ্ট্য',
      'contact_support': 'সহায়তায় যোগাযোগ করুন',
      'convert_photos': 'ছবি রূপান্তর',
      'extract_ocr': 'এক্সট্র্যাক্ট (OCR)',
      'convert_pdf': 'PDF রূপান্তর',
      'create_doc': 'ডক তৈরি',
      'no_recent_files': 'কোনো সাম্প্রতিক ফাইল নেই',
      'sort_by': 'সাজান',
      'sort_date': 'তারিখ (নতুন প্রথম)',
      'sort_name': 'নাম (A-Z)',
      'sort_size': 'আকার (বৃহত্তম প্রথম)',
      'search_hint': 'ডকুমেন্ট, PDF খুঁজুন...',
      'tab_recent': 'সাম্প্রতিক',
      'tab_pdfs': 'PDF',
      'tab_images': 'ছবি',
      'tab_ocr_text': 'OCR টেক্সট',
      'no_files_found': 'কোনো ফাইল পাওয়া যায়নি',
      'just_now': 'এইমাত্র',
      'min_ago': 'মিনিট আগে',
      'hours_ago': 'ঘন্টা আগে',
      'yesterday': 'গতকাল',
      'days_ago': 'দিন আগে',
      'all_tools': 'সব টুল',
      'pdf_tools': 'PDF টুল',
      'converters': 'কনভার্টার',
      'privacy_security': 'গোপনীয়তা ও নিরাপত্তা',
      'merge_pdf': 'PDF মার্জ',
      'split_pdf': 'PDF বিভক্ত',
      'compress_pdf': 'PDF কম্প্রেস',
      'rotate_pdf': 'PDF ঘোরান',
      'high_quality': 'উচ্চ মান',
      'fast_scan': 'দ্রুত স্ক্যান',
      'easy_edit': 'সহজ সম্পাদনা',
      'extract_data': 'ডেটা এক্সট্র্যাক্ট',
      'lock_pdf': 'PDF লক',
      'add_password_protection': 'পাসওয়ার্ড সুরক্ষা যোগ করুন',
      'unlock_pdf': 'PDF আনলক',
      'remove_restrictions': 'ডকুমেন্ট বিধিনিষেধ সরান',
      'add_signature': 'স্বাক্ষর যোগ করুন',
      'digitally_sign': 'ডিজিটালি স্বাক্ষর করুন',
      'select_ocr_language': 'OCR ভাষা নির্বাচন',
      'extract_text_title': 'AI দিয়ে টেক্সট এক্সট্র্যাক্ট',
      'extract_text_subtitle': 'আপনার ডকুমেন্ট থেকে টেক্সট এক্সট্র্যাক্ট শুরু করতে একটি উৎস নির্বাচন করুন।',
      'source_image': 'ছবি',
      'source_pdf': 'PDF',
      'source_camera': 'ক্যামেরা',
      'capture_document': 'ডকুমেন্ট ক্যাপচার',
      'select_file': 'ফাইল নির্বাচন',
      'extracting_from_image': 'ছবি থেকে টেক্সট এক্সট্র্যাক্ট হচ্ছে...',
      'extracting_from_pdf': 'PDF থেকে টেক্সট এক্সট্র্যাক্ট হচ্ছে...',
      'extracting_from_capture': 'ক্যাপচার থেকে টেক্সট এক্সট্র্যাক্ট হচ্ছে...',
      'text_extracted_success': 'টেক্সট সফলভাবে এক্সট্র্যাক্ট হয়েছে!',
      'extraction_results': 'এক্সট্র্যাকশন ফলাফল',
      'copy': 'কপি',
      'document_statistics': 'ডকুমেন্ট পরিসংখ্যান',
      'words': 'শব্দ',
      'characters': 'অক্ষর',
      'extracted_text': 'এক্সট্র্যাক্টেড টেক্সট',
      'no_text_hint': 'কোনো টেক্সট এক্সট্র্যাক্ট হয়নি। এখানে সম্পাদনা করুন...',
      'save_document': 'ডকুমেন্ট সংরক্ষণ',
      'save': 'সংরক্ষণ',
      'share': 'শেয়ার',
      'scan_result': 'স্ক্যান ফলাফল',
      'failed_to_load_image': 'ছবি লোড করতে ব্যর্থ',
      'pages_scanned_format': 'স্ক্যান করা  •  সংরক্ষণ ফরম্যাট নির্বাচন',
      'save_as': 'হিসাবে সংরক্ষণ',
      'document': 'ডকুমেন্ট',
      'share_scanned_pages': 'স্ক্যান করা পৃষ্ঠা শেয়ার',
      'saving': 'সংরক্ষণ হচ্ছে...',
      'open_settings': 'সেটিংস খুলুন',
      'camera_permission_msg': 'স্ক্যান করতে ক্যামেরা অনুমতি প্রয়োজন।',
      'permission_required': '\$name অনুমতি প্রয়োজন',
      'creating_pdf': 'PDF তৈরি হচ্ছে...',
      'delete_confirm': 'মুছুন',
      'file_options': 'ফাইল অপশন',
      'rename': 'নাম পরিবর্তন',
      'download': 'ডাউনলোড',
      'delete_confirmation': 'আপনি কি "\$fileName" মুছতে নিশ্চিত? এই কাজটি ফেরানো যাবে না।',
      'watermark_pdf': 'PDF ওয়াটারমার্ক',
      'add_text_watermark': 'PDF-এ টেক্সট ওয়াটারমার্ক যোগ করুন',
      'watermark_text': 'ওয়াটারমার্ক টেক্সট',
      'watermark_text_hint': 'ওয়াটারমার্ক টেক্সট লিখুন...',
      'watermark_opacity': 'অস্বচ্ছতা',
      'watermark_font_size': 'ফন্ট সাইজ',
      'watermark_bold': 'বোল্ড',
      'watermark_italic': 'ইটালিক',
      'watermark_tiled': 'টাইলড (পুনরাবৃত্তি প্যাটার্ন)',
      'watermark_font': 'ফন্ট পরিবার',
      'watermark_rotation': 'ঘূর্ণন',
      'watermark_success': 'ওয়াটারমার্ক সফলভাবে যোগ হয়েছে',
      'watermark_error': 'ওয়াটারমার্ক যোগ করতে ব্যর্থ',
      'watermark_text_empty': 'অনুগ্রহ করে ওয়াটারমার্ক টেক্সট লিখুন',
      'reorder_pages': 'পিডিএফ পৃষ্ঠা সাজান',
      'reorder_delete_pages': 'PDF পৃষ্ঠা পুনর্বিন্যাস বা মুছুন',
      'delete_page': 'মুছুন',
      'move_up': 'উপরে',
      'move_down': 'নিচে',
      'page': 'পৃষ্ঠা',
      'reorder_success': 'পৃষ্ঠা সফলভাবে পুনর্বিন্যাস করা হয়েছে',
      'reorder_error': 'পৃষ্ঠা পুনর্বিন্যাস করতে ব্যর্থ',
      'no_pages_to_show': 'প্রদর্শনের জন্য কোনো পৃষ্ঠা নেই',
      'qr_scanner': 'QR স্ক্যানার',
      'scan_qr_barcode': 'QR ও বারকোড স্ক্যান করুন',
      'qr_code_detected': 'কোড সনাক্ত হয়েছে',
      'qr_result': 'স্ক্যান ফলাফল',
      'qr_save_as_text': 'টেক্সট হিসেবে সংরক্ষণ',
      'qr_save_as_image': 'ছবি হিসেবে সংরক্ষণ',
      'qr_open_url': 'URL খুলুন',
      'qr_copy_text': 'টেক্সট কপি করুন',
      'qr_no_code_detected': 'এখনো কোনো কোড সনাক্ত হয়নি',
      'qr_point_at_code': 'ক্যামেরা QR কোড বা বারকোডের দিকে তাক করুন',
      'qr_saved_success': 'QR কোড সফলভাবে সংরক্ষিত হয়েছে',
      'qr_invalid_url': 'অবৈধ URL',
      'qr_scan_again': 'আবার স্ক্যান করুন',
      'qr_copied_to_clipboard': 'ক্লিপবোর্ডে কপি করা হয়েছে',
      'close': 'বন্ধ',
      'batch_ocr': 'ব্যাচ OCR',
      'batch_ocr_subtitle': 'একাধিক ছবি থেকে টেক্সট এক্সট্র্যাক্ট করুন',
      'batch_ocr_select_images': 'একাধিক ছবি নির্বাচন করুন',
      'batch_ocr_processing': 'ছবি প্রসেস হচ্ছে',
      'batch_ocr_of': 'এর',
      'batch_ocr_export_txt': 'TXT হিসেবে এক্সপোর্ট',
      'batch_ocr_export_csv': 'CSV হিসেবে এক্সপোর্ট',
      'batch_ocr_success': 'ব্যাচ OCR সফল',
      'batch_ocr_error': 'ব্যাচ OCR ব্যর্থ',
      'batch_ocr_no_text': 'কোনো ছবিতেই টেক্সট পাওয়া যায়নি',
      'batch_ocr_select_source': 'ব্যাচ OCR-এর জন্য ছবির উৎস বেছে নিন',
      'batch_ocr_from_gallery': 'গ্যালারি থেকে',
      'batch_ocr_from_camera': 'ক্যামেরা থেকে',
      'batch_ocr_captured_count': '\$count টি ছবি তোলা হয়েছে। আরও তুলবেন?',
      'batch_ocr_capture_more': 'আরও তুলুন',
      'batch_ocr_done': 'সম্পন্ন',
      'batch_ocr_results': 'ব্যাচ OCR ফলাফল',
      'export_format': 'এক্সপোর্ট ফরম্যাট',
      'ai_prompt': 'AI প্রম্পট',
      'generate_ai_prompt': 'AI প্রম্পট তৈরি করুন',
      'ai_prompt_guide': 'AI এর সাথে কীভাবে ব্যবহার করবেন',
      'ai_prompt_guide_step1': '1. তৈরি করা প্রম্পট কপি বা শেয়ার করুন',
      'ai_prompt_guide_step2': '2. আপনার প্রিয় AI অ্যাপ খুলুন (ChatGPT, Gemini, Claude ইত্যাদি)',
      'ai_prompt_guide_step3': '3. প্রম্পট পেস্ট করুন এবং AI কে পাঠান',
      'prompt_summarize': 'সারসংক্ষেপ',
      'prompt_qa': 'প্রশ্নোত্তর',
      'prompt_translate': 'অনুবাদ',
      'prompt_extract_data': 'ডেটা এক্সট্র্যাক্ট',
      'prompt_summarize_desc': 'দস্তাবেজের সংক্ষিপ্ত সারসংক্ষেপ পান',
      'prompt_qa_desc': 'দস্তাবেজ সম্পর্কে প্রশ্ন জিজ্ঞাসা করুন',
      'prompt_translate_desc': 'দস্তাবেজ ইংরেজিতে অনুবাদ করুন',
      'prompt_extract_data_desc': 'নাম, তারিখ, পরিমাণ এবং মূল তথ্য এক্সট্র্যাক্ট করুন',
      'prompt_copied': 'প্রম্পট ক্লিপবোর্ডে কপি করা হয়েছে',
      'copy_prompt': 'প্রম্পট কপি',
      'share_prompt': 'প্রম্পট শেয়ার',
      'ai_guide_title': 'AI সহকারী গাইড',
      'ai_guide_desc': 'আপনার প্রিয় AI টুল দিয়ে তৈরি প্রম্পট ব্যবহার করুন',
      'open_chatgpt': 'ChatGPT খুলুন',
      'open_gemini': 'Gemini খুলুন',
      'open_claude': 'Claude খুলুন',
      'open_copilot': 'Copilot খুলুন',
      'open_deepseek': 'DeepSeek খুলুন',
      'prompt_preview': 'প্রম্পট প্রিভিউ',
      'select_template': 'টেমপ্লেট নির্বাচন',
      'ai_tools': 'AI টুলস',
      'processing': 'প্রসেসিং...',
      'may_take_a_while': 'বড় ফাইলের জন্য এতে কিছুটা সময় লাগতে পারে।',
      'notify_when_ready': 'প্রস্তুত হলে জানান',
      'save_as_copy': 'কপি হিসেবে সংরক্ষণ',
      'watermark_preview': 'প্রিভিউ',
      'watermark_apply': 'ওয়াটারমার্ক প্রয়োগ',
      'open_perplexity': 'Perplexity খুলুন',
      'open_mistral': 'Mistral খুলুন',
      'open_grok': 'Grok খুলুন',
      'open_meta_ai': 'Meta AI খুলুন',
      'open_you_com': 'You.com খুলুন',
      'open_pi': 'Pi খুলুন',
      'open_ai_failed': 'AI অ্যাপ খোলা যায়নি। আবার চেষ্টা করুন।',
      'draw_signature': 'স্বাক্ষর আঁকুন',
      'please_sign': 'নিচের সাদা বাক্সের ভিতরে স্বাক্ষর করুন।',
      'undo': 'পূর্বাবস্থায় ফিরুন',
      'page_of': 'পৃষ্ঠা \$current of \$total',
      'drag_scale_signature': 'স্বাক্ষর টেনে আনুন ও স্কেল করুন',
      'confirm_save_stamp': 'নিশ্চিত করুন ও স্ট্যাম্প সংরক্ষণ করুন',
      'theme_light': 'হালকা',
      'theme_dark': 'গাঢ়',
      'theme_system': 'সিস্টেম',
      'quality_low': 'কম',
      'quality_medium': 'মাঝারি',
      'quality_high': 'উচ্চ',
      'quality_ultra': 'আল্ট্রা',
      'clear_cache_confirm': 'এটি সমস্ত ক্যাশে ফাইল (\$size) মুছে ফেলবে। চালিয়ে যাবেন?',
    },
    'hi': {
      'title': 'आरएम-स्कैनर एआई',
      'onboard_title_1': 'कहीं भी स्कैन करें',
      'onboard_desc_1':
          'उच्च गुणवत्ता और स्वतः किनारा पहचान के साथ कहीं भी आसानी से दस्तावेज़ स्कैन करें।',
      'onboard_title_2': 'स्मार्ट OCR',
      'onboard_desc_2':
          'अपने स्कैन किए गए दस्तावेज़ों से कई भाषाओं में तुरंत टेक्स्ट निकालें।',
      'onboard_title_3': 'व्यवस्थित करें और साझा करें',
      'onboard_desc_3':
          'स्कैन को PDF में बदलें, फ़ाइलें व्यवस्थित करें और सुरक्षित रूप से साझा करें।',
      'skip': 'छोड़ें',
      'start': 'शुरू',
      'home': 'होम',
      'files': 'फ़ाइलें',
      'tools': 'टूल्स',
      'ocr': 'ओसीआर',
      'profile': 'प्रोफ़ाइल',
      'scan_doc': 'दस्तावेज़ स्कैन',
      'scan_subtitle': 'रसीदें, नोट्स और आईडी कैप्चर करें',
      'quick_actions': 'त्वरित कार्य',
      'recent_files': 'हाल की फ़ाइलें',
      'see_all': 'सभी देखें',
      'see_all_tools': 'सभी टूल देखें',
      'image_to_pdf': 'इमेज से पीडीएफ',
      'image_to_text': 'इमेज से टेक्स्ट',
      'pdf_to_text': 'पीडीएफ से टेक्स्ट',
      'pdf_to_image': 'पीडीएफ से छवि',
      'text_to_pdf': 'टेक्स्ट से पीडीएफ',
      'settings': 'सेटिंग्स',
      'basic': 'बुनियादी',
      'scan': 'स्कैन',
      'pdf_ocr_section': 'पीडीएफ और ओसीआर',
      'data': 'डेटा',
      'theme': 'थीम',
      'language': 'भाषा',
      'auto_enhance': 'ऑटो एनहांस',
      'scan_quality': 'स्कैन गुणवत्ता',
      'default_page_size': 'पेज साइज',
      'ocr_language': 'ओसीआर भाषा',
      'clear_cache': 'कैश साफ़ करें',
      'confirm': 'पुष्टि करें',
      'cancel': 'रद्द करें',
      'upgrade_title': 'निःशुल्क उपयोगकर्ता',
      'upgrade_subtitle': 'सभी सुविधाओं को अनलॉक करने के लिए अपग्रेड करें',
      'upgrade_button': 'अपग्रेड',
      'refer_friend': 'मित्र को रेफर करें',
      'scan_section': 'स्कैन प्राथमिकताएं',
      'support_privacy': 'सहायता और गोपनीयता',
      'privacy_policy': 'गोपनीयता नीति',
      'feature_request': 'सुविधा का अनुरोध',
      'report_bug': 'बग रिपोर्ट',
      'support_developer': 'डेवलपर का समर्थन करें',
      'loading_support_ad': 'विज्ञापन लोड हो रहा है...',
      'thank_you_support': 'आपके समर्थन के लिए धन्यवाद!',
      'ad_not_ready':
          'विज्ञापन अभी तैयार नहीं है। कृपया बाद में पुनः प्रयास करें।',
      'data_section': 'डेटा प्रबंधन',
      'use_system_font': 'सिस्टम फ़ॉन्ट',
      'system_font': 'सिस्टम',
      'app_font': 'ऐप फ़ॉन्ट (SamsungOne)',
      'saved_to_downloads': 'डाउनलोड फ़ोल्डर में सहेजा गया',
      'could_not_save_permission': 'सहेजा नहीं जा सका: स्टोरेज अनुमति दें।',
      'could_not_open_file': 'फ़ाइल नहीं खोली जा सकी।',
      'error_opening_file': 'फ़ाइल खोलते समय त्रुटि हुई।',
      'scan_error': 'स्कैन करते समय त्रुटि हुई। कृपया पुनः प्रयास करें।',
      'pdf_created_successfully': 'PDF सफलतापूर्वक बनाया गया',
      'image_to_pdf_success': 'छवि से PDF सफलतापूर्वक बनाया गया',
      'pdfs_merged_success': 'PDF सफलतापूर्वक मिलाए गए',
      'pdf_split_success': 'PDF सफलतापूर्वक विभाजित किया गया',
      'pdf_compressed_success': 'PDF सफलतापूर्वक संक्षिप्त किया गया',
      'pdf_rotated_success': 'PDF सफलतापूर्वक घुमाया गया',
      'pdf_locked_success': 'PDF सफलतापूर्वक लॉक किया गया',
      'pdf_unlocked_success': 'PDF सफलतापूर्वक अनलॉक किया गया',
      'incorrect_password': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'failed_to_unlock': 'PDF अनलॉक करने में विफल। कृपया पुनः प्रयास करें।',
      'pdf_to_image_success': 'PDF से छवि सफल',
      'pdf_to_text_success': 'PDF से टेक्स्ट सफल',
      'signature_saved': 'हस्ताक्षर सफलतापूर्वक सहेजा गया',
      'text_to_pdf_error': 'टेक्स्ट को PDF में बदलने में विफल। कृपया पुनः प्रयास करें।',
      'error_prefix': 'एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।',
      'pdf_saved_successfully': 'PDF सफलतापूर्वक सहेजा गया',
      'document_saved_successfully': 'दस्तावेज़ सफलतापूर्वक सहेजा गया',
      'error_saving_doc': 'दस्तावेज़ सहेजना विफल। स्टोरेज अनुमति जांचें।',
      'error_sharing':
          'दस्तावेज़ साझा नहीं किया जा सका। कृपया पुनः प्रयास करें।',
      'text_copied': 'टेक्स्ट क्लिपबोर्ड पर कॉपी हुआ',
      'saved_success_text': 'टेक्स्ट फ़ाइल के रूप में सफलतापूर्वक सहेजा गया।',
      'error_picking_image': 'छवि चुनी नहीं जा सकी। कृपया पुनः प्रयास करें।',
      'error_picking_pdf': 'PDF नहीं खोली जा सकी। कृपया पुनः प्रयास करें।',
      'error_capturing_image': 'फोटो नहीं ली जा सकी। कैमरा जांचें।',
      'cache_cleared': 'कैश साफ़ किया गया',
      'images_saved': 'छवि सफलतापूर्वक सहेजी गई',
      'invalid_page_range': 'अमान्य पृष्ठ श्रेणी',
      'already_protected': 'यह PDF पहले से पासवर्ड सुरक्षित है।',
      'not_protected': 'यह PDF पासवर्ड सुरक्षित नहीं है।',
      'could_not_open_privacy_policy': 'गोपनीयता नीति नहीं खोली जा सकी',
      'could_not_open_email': 'ईमेल ऐप नहीं खोला जा सका',
      'deleted_successfully': '\$fileType सफलतापूर्वक हटाया गया',
      'no_text_in_pdf': 'PDF में कोई टेक्स्ट नहीं मिला',
      'no_text_in_image': 'छवि में कोई टेक्स्ट नहीं मिला',
      'clear': 'साफ़ करें',
      'menu': 'मेनू',
      'about': 'के बारे में',
      'about_description': 'RMScanner AI एक मुफ्त, ऑल-इन-वन दस्तावेज़ स्कैनर ऐप है जिसमें OCR, PDF टूल और QR स्कैनर है। कभी भी, कहीं भी अपने दस्तावेज़ों को स्कैन करें, रूपांतरित करें और साझा करें।',
      'app_version': 'संस्करण',
      'developed_by': 'द्वारा विकसित',
      'features': 'विशेषताएं',
      'contact_support': 'सहायता से संपर्क करें',
      'convert_photos': 'फ़ोटो रूपांतरण',
      'extract_ocr': 'एक्सट्रैक्ट (OCR)',
      'convert_pdf': 'PDF रूपांतरण',
      'create_doc': 'डॉक बनाएं',
      'no_recent_files': 'कोई हाल की फ़ाइल नहीं',
      'sort_by': 'क्रमबद्ध करें',
      'sort_date': 'तारीख (नवीनतम पहले)',
      'sort_name': 'नाम (A-Z)',
      'sort_size': 'आकार (सबसे बड़ा पहले)',
      'search_hint': 'दस्तावेज़, PDF खोजें...',
      'tab_recent': 'हाल का',
      'tab_pdfs': 'PDF',
      'tab_images': 'छवियां',
      'tab_ocr_text': 'OCR टेक्स्ट',
      'no_files_found': 'कोई फ़ाइल नहीं मिली',
      'just_now': 'अभी',
      'min_ago': 'मिनट पहले',
      'hours_ago': 'घंटे पहले',
      'yesterday': 'कल',
      'days_ago': 'दिन पहले',
      'all_tools': 'सभी टूल',
      'pdf_tools': 'PDF टूल',
      'converters': 'कनवर्टर',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'merge_pdf': 'PDF मर्ज',
      'split_pdf': 'PDF विभाजित',
      'compress_pdf': 'PDF कम्प्रेस',
      'rotate_pdf': 'PDF घुमाएं',
      'high_quality': 'उच्च गुणवत्ता',
      'fast_scan': 'तेज़ स्कैन',
      'easy_edit': 'आसान संपादन',
      'extract_data': 'डेटा एक्सट्रैक्ट',
      'lock_pdf': 'PDF लॉक',
      'add_password_protection': 'पासवर्ड सुरक्षा जोड़ें',
      'unlock_pdf': 'PDF अनलॉक',
      'remove_restrictions': 'दस्तावेज़ प्रतिबंध हटाएं',
      'add_signature': 'हस्ताक्षर जोड़ें',
      'digitally_sign': 'डिजिटल रूप से हस्ताक्षर',
      'select_ocr_language': 'OCR भाषा चुनें',
      'extract_text_title': 'AI के साथ टेक्स्ट एक्सट्रैक्ट',
      'extract_text_subtitle': 'अपने दस्तावेज़ों से टेक्स्ट निकालना शुरू करने के लिए एक स्रोत चुनें।',
      'source_image': 'छवि',
      'source_pdf': 'PDF',
      'source_camera': 'कैमरा',
      'capture_document': 'दस्तावेज़ कैप्चर',
      'select_file': 'फ़ाइल चुनें',
      'extracting_from_image': 'छवि से टेक्स्ट निकाला जा रहा है...',
      'extracting_from_pdf': 'PDF से टेक्स्ट निकाला जा रहा है...',
      'extracting_from_capture': 'कैप्चर से टेक्स्ट निकाला जा रहा है...',
      'text_extracted_success': 'टेक्स्ट सफलतापूर्वक निकाला गया!',
      'extraction_results': 'एक्सट्रैक्शन परिणाम',
      'copy': 'कॉपी',
      'document_statistics': 'दस्तावेज़ आँकड़े',
      'words': 'शब्द',
      'characters': 'अक्षर',
      'extracted_text': 'निकाला गया टेक्स्ट',
      'no_text_hint': 'कोई टेक्स्ट नहीं निकाला गया। यहाँ संपादित करें...',
      'save_document': 'दस्तावेज़ सहेजें',
      'save': 'सहेजें',
      'share': 'शेयर',
      'scan_result': 'स्कैन परिणाम',
      'failed_to_load_image': 'छवि लोड करने में विफल',
      'pages_scanned_format': 'स्कैन किया  •  सहेजने का प्रारूप चुनें',
      'save_as': 'इस रूप में सहेजें',
      'document': 'दस्तावेज़',
      'share_scanned_pages': 'स्कैन किए गए पृष्ठ शेयर',
      'saving': 'सहेज रहे हैं...',
      'open_settings': 'सेटिंग्स खोलें',
      'camera_permission_msg': 'स्कैन करने के लिए कैमरा अनुमति आवश्यक है।',
      'permission_required': '\$name अनुमति आवश्यक',
      'creating_pdf': 'PDF बनाई जा रही है...',
      'delete_confirm': 'हटाएं',
      'file_options': 'फ़ाइल विकल्प',
      'rename': 'नाम बदलें',
      'download': 'डाउनलोड',
      'delete_confirmation': 'क्या आप "\$fileName" हटाने के लिए सुनिश्चित हैं? यह कार्य वापस नहीं किया जा सकता।',
      'watermark_pdf': 'PDF वॉटरमार्क',
      'add_text_watermark': 'PDF में टेक्स्ट वॉटरमार्क जोड़ें',
      'watermark_text': 'वॉटरमार्क टेक्स्ट',
      'watermark_text_hint': 'वॉटरमार्क टेक्स्ट दर्ज करें...',
      'watermark_opacity': 'अपारदर्शिता',
      'watermark_font_size': 'फ़ॉन्ट आकार',
      'watermark_bold': 'बोल्ड',
      'watermark_italic': 'इटैलिक',
      'watermark_tiled': 'टाइल्ड (दोहराया गया पैटर्न)',
      'watermark_font': 'फ़ॉन्ट परिवार',
      'watermark_rotation': 'घूर्णन',
      'watermark_success': 'वॉटरमार्क सफलतापूर्वक जोड़ा गया',
      'watermark_error': 'वॉटरमार्क जोड़ने में विफल',
      'watermark_text_empty': 'कृपया वॉटरमार्क टेक्स्ट दर्ज करें',
      'reorder_pages': 'पीडीएफ पृष्ठ व्यवस्थित करें',
      'reorder_delete_pages': 'PDF पृष्ठ पुनर्व्यवस्थित या हटाएं',
      'delete_page': 'हटाएं',
      'move_up': 'ऊपर ले जाएं',
      'move_down': 'नीचे ले जाएं',
      'page': 'पृष्ठ',
      'reorder_success': 'पृष्ठ सफलतापूर्वक पुनर्व्यवस्थित किए गए',
      'reorder_error': 'पृष्ठ पुनर्व्यवस्थित करने में विफल',
      'no_pages_to_show': 'प्रदर्शित करने के लिए कोई पृष्ठ नहीं',
      'qr_scanner': 'QR स्कैनर',
      'scan_qr_barcode': 'QR और बारकोड स्कैन करें',
      'qr_code_detected': 'कोड का पता चला',
      'qr_result': 'स्कैन परिणाम',
      'qr_save_as_text': 'टेक्स्ट के रूप में सहेजें',
      'qr_save_as_image': 'छवि के रूप में सहेजें',
      'qr_open_url': 'URL खोलें',
      'qr_copy_text': 'टेक्स्ट कॉपी करें',
      'qr_no_code_detected': 'अभी तक कोई कोड नहीं मिला',
      'qr_point_at_code': 'अपने कैमरे को QR कोड या बारकोड पर लक्षित करें',
      'qr_saved_success': 'QR कोड सफलतापूर्वक सहेजा गया',
      'qr_invalid_url': 'अमान्य URL',
      'qr_scan_again': 'फिर से स्कैन करें',
      'qr_copied_to_clipboard': 'क्लिपबोर्ड पर कॉपी किया गया',
      'close': 'बंद करें',
      'batch_ocr': 'बैच OCR',
      'batch_ocr_subtitle': 'एकाधिक छवियों से टेक्स्ट निकालें',
      'batch_ocr_select_images': 'एकाधिक छवियां चुनें',
      'batch_ocr_processing': 'छवि संसाधित हो रही है',
      'batch_ocr_of': 'का',
      'batch_ocr_export_txt': 'TXT के रूप में निर्यात करें',
      'batch_ocr_export_csv': 'CSV के रूप में निर्यात करें',
      'batch_ocr_success': 'बैच OCR सफल',
      'batch_ocr_error': 'बैच OCR विफल',
      'batch_ocr_no_text': 'किसी भी छवि में कोई टेक्स्ट नहीं मिला',
      'batch_ocr_select_source': 'बैच OCR के लिए छवि स्रोत चुनें',
      'batch_ocr_from_gallery': 'गैलरी से',
      'batch_ocr_from_camera': 'कैमरा से',
      'batch_ocr_captured_count': '\$count छवि(यां) कैप्चर की गईं। और कैप्चर करें?',
      'batch_ocr_capture_more': 'और कैप्चर करें',
      'batch_ocr_done': 'पूर्ण',
      'batch_ocr_results': 'बैच OCR परिणाम',
      'export_format': 'निर्यात प्रारूप',
      'ai_prompt': 'AI प्रॉम्प्ट',
      'generate_ai_prompt': 'AI प्रॉम्प्ट बनाएं',
      'ai_prompt_guide': 'AI के साथ कैसे उपयोग करें',
      'ai_prompt_guide_step1': '1. बनाए गए प्रॉम्प्ट को कॉपी या शेयर करें',
      'ai_prompt_guide_step2': '2. अपना पसंदीदा AI ऐप खोलें (ChatGPT, Gemini, Claude, आदि)',
      'ai_prompt_guide_step3': '3. प्रॉम्प्ट पेस्ट करें और AI को भेजें',
      'prompt_summarize': 'सारांश',
      'prompt_qa': 'प्रश्न-उत्तर',
      'prompt_translate': 'अनुवाद',
      'prompt_extract_data': 'डेटा निकालें',
      'prompt_summarize_desc': 'दस्तावेज़ का संक्षिप्त सारांश प्राप्त करें',
      'prompt_qa_desc': 'दस्तावेज़ के बारे में प्रश्न पूछें',
      'prompt_translate_desc': 'दस्तावेज़ का अंग्रेजी में अनुवाद करें',
      'prompt_extract_data_desc': 'नाम, तिथियाँ, राशियाँ और मुख्य जानकारी निकालें',
      'prompt_copied': 'प्रॉम्प्ट क्लिपबोर्ड पर कॉपी हो गया',
      'copy_prompt': 'प्रॉम्प्ट कॉपी',
      'share_prompt': 'प्रॉम्प्ट शेयर',
      'ai_guide_title': 'AI सहायक गाइड',
      'ai_guide_desc': 'अपने पसंदीदा AI टूल के साथ बनाए गए प्रॉम्प्ट का उपयोग करें',
      'open_chatgpt': 'ChatGPT खोलें',
      'open_gemini': 'Gemini खोलें',
      'open_claude': 'Claude खोलें',
      'open_copilot': 'Copilot खोलें',
      'open_deepseek': 'DeepSeek खोलें',
      'prompt_preview': 'प्रॉम्प्ट पूर्वावलोकन',
      'select_template': 'टेम्पलेट चुनें',
      'ai_tools': 'AI टूल्स',
      'processing': 'प्रोसेसिंग...',
      'may_take_a_while': 'बड़े फ़ाइलों के लिए इसमें कुछ समय लग सकता है।',
      'notify_when_ready': 'तैयार होने पर सूचित करें',
      'save_as_copy': 'प्रतिलिपि के रूप में सहेजें',
      'watermark_preview': 'पूर्वावलोकन',
      'watermark_apply': 'वॉटरमार्क लागू करें',
      'open_perplexity': 'Perplexity खोलें',
      'open_mistral': 'Mistral खोलें',
      'open_grok': 'Grok खोलें',
      'open_meta_ai': 'Meta AI खोलें',
      'open_you_com': 'You.com खोलें',
      'open_pi': 'Pi खोलें',
      'open_ai_failed': 'AI ऐप नहीं खुला। कृपया पुनः प्रयास करें।',
      'draw_signature': 'हस्ताक्षर बनाएं',
      'please_sign': 'कृपया नीचे सफेद बॉक्स के अंदर हस्ताक्षर करें।',
      'undo': 'पूर्ववत करें',
      'page_of': 'पृष्ठ \$current of \$total',
      'drag_scale_signature': 'हस्ताक्षर खींचें और स्केल करें',
      'confirm_save_stamp': 'पुष्टि करें और स्टैम्प सहेजें',
      'theme_light': 'हल्का',
      'theme_dark': 'गहरा',
      'theme_system': 'सिस्टम',
      'quality_low': 'कम',
      'quality_medium': 'मध्यम',
      'quality_high': 'उच्च',
      'quality_ultra': 'अल्ट्रा',
      'clear_cache_confirm': 'यह सभी कैश फ़ाइलों (\$size) को हटा देगा। जारी रखें?',
    },
    'fr': {
      'title': 'RMScanner AI',
      'onboard_title_1': 'Scanner Partout',
      'onboard_desc_1':
          'Scannez facilement des documents en déplacement avec une haute qualité et une détection automatique des bords.',
      'onboard_title_2': 'OCR Intelligent',
      'onboard_desc_2':
          'Extrayez le texte de vos documents scannés dans plusieurs langues instantanément.',
      'onboard_title_3': 'Organiser & Partager',
      'onboard_desc_3':
          'Convertissez les scans en PDF, organisez les fichiers et partagez-les en toute sécurité.',
      'skip': 'PASSER',
      'start': 'DÉMARRER',
      'home': 'Accueil',
      'files': 'Fichiers',
      'tools': 'Outils',
      'ocr': 'OCR',
      'profile': 'Profil',
      'scan_doc': 'Scanner doc',
      'scan_subtitle': 'Capturer reçus, notes et identités',
      'quick_actions': 'Actions rapides',
      'recent_files': 'Fichiers récents',
      'see_all': 'Voir tout',
      'see_all_tools': 'Voir tous les outils',
      'image_to_pdf': 'Image en PDF',
      'image_to_text': 'Image en texte',
      'pdf_to_text': 'PDF en texte',
      'pdf_to_image': 'PDF en image',
      'text_to_pdf': 'Texte en PDF',
      'settings': 'Paramètres',
      'basic': 'Basique',
      'scan': 'Scanner',
      'pdf_ocr_section': 'PDF et OCR',
      'data': 'Données',
      'theme': 'Thème',
      'language': 'Langue',
      'auto_enhance': 'Amélioration auto',
      'scan_quality': 'Qualité scan',
      'default_page_size': 'Taille page',
      'ocr_language': 'Langue OCR',
      'clear_cache': 'Vider le cache',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'upgrade_title': 'Utilisateur gratuit',
      'upgrade_subtitle': 'Passer à la version Premium',
      'upgrade_button': 'Améliorer',
      'refer_friend': 'Parrainer un ami',
      'scan_section': 'Préférences de numérisation',
      'support_privacy': 'Assistance et confidentialité',
      'privacy_policy': 'Politique de confidentialité',
      'feature_request': 'Demande de fonctionnalité',
      'report_bug': 'Signaler un bug',
      'support_developer': 'Soutenir le développeur',
      'loading_support_ad': 'Chargement de la publicité...',
      'thank_you_support': 'Merci pour votre soutien !',
      'ad_not_ready':
          "La publicité n'est pas encore prête. Veuillez réessayer plus tard.",
      'data_section': 'Gestion des données',
      'use_system_font': 'Police système',
      'system_font': 'Système',
      'app_font': "Police de l'application (SamsungOne)",
      'saved_to_downloads': 'Enregistré dans le dossier Downloads',
      'could_not_save_permission':
          "Enregistrement impossible : autorisez l'accès au stockage.",
      'could_not_open_file': "Impossible d'ouvrir le fichier.",
      'error_opening_file':
          "Une erreur s'est produite lors de l'ouverture du fichier.",
      'scan_error':
          "Une erreur s'est produite lors du scan. Veuillez réessayer.",
      'pdf_created_successfully': 'PDF créé avec succès',
      'image_to_pdf_success': 'Image vers PDF créé avec succès',
      'pdfs_merged_success': 'PDF fusionnés avec succès',
      'pdf_split_success': 'PDF divisé avec succès',
      'pdf_compressed_success': 'PDF compressé avec succès',
      'pdf_rotated_success': 'PDF pivoté avec succès',
      'pdf_locked_success': 'PDF verrouillé avec succès',
      'pdf_unlocked_success': 'PDF déverrouillé avec succès',
      'incorrect_password': 'Mot de passe incorrect. Veuillez réessayer.',
      'failed_to_unlock': 'Échec du déverrouillage du PDF. Veuillez réessayer.',
      'pdf_to_image_success': 'PDF vers image réussi',
      'pdf_to_text_success': 'PDF vers texte réussi',
      'signature_saved': 'Signature enregistrée avec succès',
      'text_to_pdf_error': 'Échec de la conversion du texte en PDF. Veuillez réessayer.',
      'error_prefix':
          "Une erreur inattendue s'est produite. Veuillez réessayer.",
      'pdf_saved_successfully': 'PDF enregistré avec succès',
      'document_saved_successfully': 'Document enregistré avec succès',
      'error_saving_doc':
          "Échec de l'enregistrement. Vérifiez les autorisations de stockage.",
      'error_sharing':
          'Impossible de partager le document. Veuillez réessayer.',
      'text_copied': 'Texte copié dans le presse-papiers',
      'saved_success_text': 'Enregistré avec succès en tant que fichier texte.',
      'error_picking_image':
          "Impossible de sélectionner l'image. Veuillez réessayer.",
      'error_picking_pdf': "Impossible d'ouvrir le PDF. Veuillez réessayer.",
      'error_capturing_image':
          'Impossible de prendre la photo. Vérifiez votre caméra.',
      'cache_cleared': 'Cache vidée',
      'images_saved': 'image(s) enregistrée(s) avec succès',
      'invalid_page_range': 'Plage de pages invalide',
      'already_protected': 'Ce PDF est déjà protégé par mot de passe.',
      'not_protected': "Ce PDF n'est pas protégé par mot de passe.",
      'could_not_open_privacy_policy':
          "Impossible d'ouvrir la politique de confidentialité",
      'could_not_open_email': "Impossible d'ouvrir l'application Email",
      'deleted_successfully': '\$fileType supprimé avec succès',
      'no_text_in_pdf': 'Aucun texte trouvé dans le PDF',
      'no_text_in_image': "Aucun texte trouvé dans l'image",
      'clear': 'Vider',
      'menu': 'Menu',
      'about': 'À propos',
      'about_description': 'RMScanner AI est une application gratuite de numérisation de documents tout-en-un avec OCR, outils PDF et scanner QR. Numérisez, convertissez et partagez vos documents à tout moment, partout.',
      'app_version': 'Version',
      'developed_by': 'Développé par',
      'features': 'Fonctionnalités',
      'contact_support': 'Contacter le support',
      'convert_photos': 'Convertir photos',
      'extract_ocr': 'Extraire (OCR)',
      'convert_pdf': 'Convertir PDF',
      'create_doc': 'Créer Doc',
      'no_recent_files': 'Aucun fichier récent',
      'sort_by': 'Trier par',
      'sort_date': 'Date (Plus récent)',
      'sort_name': 'Nom (A-Z)',
      'sort_size': 'Taille (Plus grand)',
      'search_hint': 'Rechercher documents, PDF...',
      'tab_recent': 'Récents',
      'tab_pdfs': 'PDF',
      'tab_images': 'Images',
      'tab_ocr_text': 'Texte OCR',
      'no_files_found': 'Aucun fichier trouvé',
      'just_now': 'À l\'instant',
      'min_ago': 'min',
      'hours_ago': 'h',
      'yesterday': 'Hier',
      'days_ago': 'jours',
      'all_tools': 'Tous les outils',
      'pdf_tools': 'Outils PDF',
      'converters': 'Convertisseurs',
      'privacy_security': 'Confidentialité & Sécurité',
      'merge_pdf': 'Fusionner PDF',
      'split_pdf': 'Diviser PDF',
      'compress_pdf': 'Compresser PDF',
      'rotate_pdf': 'Pivoter PDF',
      'high_quality': 'HAUTE QUALITÉ',
      'fast_scan': 'SCAN RAPIDE',
      'easy_edit': 'ÉDITION FACILE',
      'extract_data': 'EXTRAIRE DONNÉES',
      'lock_pdf': 'Verrouiller PDF',
      'add_password_protection': 'Ajouter une protection par mot de passe',
      'unlock_pdf': 'Déverrouiller PDF',
      'remove_restrictions': 'Supprimer les restrictions du document',
      'add_signature': 'Ajouter Signature',
      'digitally_sign': 'Signer numériquement les documents',
      'select_ocr_language': 'Sélectionner la langue OCR',
      'extract_text_title': 'Extraire le Texte avec IA',
      'extract_text_subtitle': 'Sélectionnez une source pour commencer à extraire le texte de vos documents.',
      'source_image': 'Image',
      'source_pdf': 'PDF',
      'source_camera': 'Caméra',
      'capture_document': 'Capturer Document',
      'select_file': 'Sélectionner Fichier',
      'extracting_from_image': "Extraction du texte de l'image...",
      'extracting_from_pdf': 'Extraction du texte du PDF...',
      'extracting_from_capture': 'Extraction du texte de la capture...',
      'text_extracted_success': 'Texte extrait avec succès !',
      'extraction_results': "Résultats d'Extraction",
      'copy': 'Copier',
      'document_statistics': 'Statistiques du Document',
      'words': 'mots',
      'characters': 'caractères',
      'extracted_text': 'Texte Extrait',
      'no_text_hint': "Aucun texte extrait. Essayez d'éditer ici...",
      'save_document': 'Enregistrer Document',
      'save': 'Enregistrer',
      'share': 'Partager',
      'scan_result': 'Résultat du Scan',
      'failed_to_load_image': 'Échec du chargement de l\'image',
      'pages_scanned_format': 'scannés  •  Choisir le format',
      'save_as': 'Enregistrer sous',
      'document': 'Document',
      'share_scanned_pages': 'Partager les Pages Scannées',
      'saving': 'Enregistrement...',
      'open_settings': 'Ouvrir les Paramètres',
      'camera_permission_msg': "L'autorisation de la caméra est requise pour scanner.",
      'permission_required': 'Autorisation \$name Requise',
      'creating_pdf': 'Création du PDF...',
      'delete_confirm': 'Supprimer',
      'file_options': 'Options du Fichier',
      'rename': 'Renommer',
      'download': 'Télécharger',
      'delete_confirmation': 'Êtes-vous sûr de vouloir supprimer "\$fileName"? Cette action est irréversible.',
      'watermark_pdf': 'Filigrane PDF',
      'add_text_watermark': 'Ajouter un filigrane texte au PDF',
      'watermark_text': 'Texte du filigrane',
      'watermark_text_hint': 'Saisir le texte du filigrane...',
      'watermark_opacity': 'Opacité',
      'watermark_font_size': 'Taille de police',
      'watermark_bold': 'Gras',
      'watermark_italic': 'Italique',
      'watermark_tiled': 'En mosaïque (motif répété)',
      'watermark_font': 'Famille de police',
      'watermark_rotation': 'Rotation',
      'watermark_success': 'Filigrane ajouté avec succès',
      'watermark_error': "Échec de l'ajout du filigrane",
      'watermark_text_empty': 'Veuillez saisir le texte du filigrane',
      'reorder_pages': 'Organiser les pages PDF',
      'reorder_delete_pages': 'Réorganiser ou supprimer des pages PDF',
      'delete_page': 'Supprimer',
      'move_up': 'Monter',
      'move_down': 'Descendre',
      'page': 'Page',
      'reorder_success': 'Pages réorganisées avec succès',
      'reorder_error': 'Échec de la réorganisation des pages',
      'no_pages_to_show': 'Aucune page à afficher',
      'qr_scanner': 'Scanner QR',
      'scan_qr_barcode': 'Scanner QR et code-barres',
      'qr_code_detected': 'Code détecté',
      'qr_result': 'Résultat du scan',
      'qr_save_as_text': 'Enregistrer en texte',
      'qr_save_as_image': 'Enregistrer en image',
      'qr_open_url': "Ouvrir l'URL",
      'qr_copy_text': 'Copier le texte',
      'qr_no_code_detected': 'Aucun code détecté pour le moment',
      'qr_point_at_code': 'Pointez votre caméra vers un code QR ou code-barres',
      'qr_saved_success': 'Code QR enregistré avec succès',
      'qr_invalid_url': 'URL invalide',
      'qr_scan_again': 'Scanner à nouveau',
      'qr_copied_to_clipboard': 'Copié dans le presse-papiers',
      'close': 'Fermer',
      'batch_ocr': 'OCR par lot',
      'batch_ocr_subtitle': 'Extraire le texte de plusieurs images',
      'batch_ocr_select_images': 'Sélectionner plusieurs images',
      'batch_ocr_processing': "Traitement de l'image",
      'batch_ocr_of': 'sur',
      'batch_ocr_export_txt': 'Exporter en TXT',
      'batch_ocr_export_csv': 'Exporter en CSV',
      'batch_ocr_success': 'OCR par lot réussi',
      'batch_ocr_error': "Échec de l'OCR par lot",
      'batch_ocr_no_text': 'Aucun texte trouvé dans les images',
      'batch_ocr_select_source': 'Choisir la source d\'images pour l\'OCR par lot',
      'batch_ocr_from_gallery': 'Depuis la galerie',
      'batch_ocr_from_camera': 'Depuis l\'appareil photo',
      'batch_ocr_captured_count': '\$count image(s) capturée(s). Capturer plus ?',
      'batch_ocr_capture_more': 'Capturer plus',
      'batch_ocr_done': 'Terminé',
      'batch_ocr_results': 'Résultats OCR par lot',
      'export_format': "Format d'export",
      'ai_prompt': 'Prompt IA',
      'generate_ai_prompt': 'Générer un Prompt IA',
      'ai_prompt_guide': "Comment utiliser avec l'IA",
      'ai_prompt_guide_step1': '1. Copiez ou partagez le prompt généré',
      'ai_prompt_guide_step2': '2. Ouvrez votre application IA préférée (ChatGPT, Gemini, Claude, etc.)',
      'ai_prompt_guide_step3': "3. Collez le prompt et envoyez-le à l'IA",
      'prompt_summarize': 'Résumer',
      'prompt_qa': 'Q&R',
      'prompt_translate': 'Traduire',
      'prompt_extract_data': 'Extraire Données',
      'prompt_summarize_desc': 'Obtenez un résumé concis du document',
      'prompt_qa_desc': 'Posez des questions sur le document',
      'prompt_translate_desc': 'Traduisez le document en anglais',
      'prompt_extract_data_desc': 'Extrayez noms, dates, montants et infos clés',
      'prompt_copied': 'Prompt copié dans le presse-papiers',
      'copy_prompt': 'Copier le Prompt',
      'share_prompt': 'Partager le Prompt',
      'ai_guide_title': 'Guide Assistant IA',
      'ai_guide_desc': 'Utilisez le prompt généré avec votre outil IA préféré',
      'open_chatgpt': 'Ouvrir ChatGPT',
      'open_gemini': 'Ouvrir Gemini',
      'open_claude': 'Ouvrir Claude',
      'open_copilot': 'Ouvrir Copilot',
      'open_deepseek': 'Ouvrir DeepSeek',
      'prompt_preview': 'Aperçu du Prompt',
      'select_template': 'Sélectionner un Modèle',
      'ai_tools': 'Outils IA',
      'processing': 'Traitement...',
      'may_take_a_while': "Cela peut prendre du temps pour les gros fichiers.",
      'notify_when_ready': 'Notifier quand prêt',
      'save_as_copy': 'Enregistrer comme copie',
      'watermark_preview': 'Aperçu',
      'watermark_apply': 'Appliquer le filigrane',
      'open_perplexity': 'Ouvrir Perplexity',
      'open_mistral': 'Ouvrir Mistral',
      'open_grok': 'Ouvrir Grok',
      'open_meta_ai': 'Ouvrir Meta AI',
      'open_you_com': 'Ouvrir You.com',
      'open_pi': 'Ouvrir Pi',
      'open_ai_failed': "Impossible d'ouvrir l'application IA. Veuillez réessayer.",
      'draw_signature': 'Dessiner la signature',
      'please_sign': 'Veuillez signer dans le cadre blanc ci-dessous.',
      'undo': 'Annuler',
      'page_of': 'Page \$current sur \$total',
      'drag_scale_signature': 'Glisser & Redimensionner la signature',
      'confirm_save_stamp': 'Confirmer & Enregistrer le tampon',
      'theme_light': 'Clair',
      'theme_dark': 'Sombre',
      'theme_system': 'Système',
      'quality_low': 'Bas',
      'quality_medium': 'Moyen',
      'quality_high': 'Élevé',
      'quality_ultra': 'Ultra',
      'clear_cache_confirm': 'Cela supprimera tous les fichiers en cache (\$size). Continuer ?',
    },
    'de': {
      'title': 'RMScanner AI',
      'onboard_title_1': 'Überall Scannen',
      'onboard_desc_1':
          'Scannen Sie Dokumente unterwegs einfach mit hoher Qualität und automatischer Kantenerkennung.',
      'onboard_title_2': 'Smarte OCR',
      'onboard_desc_2':
          'Extrahieren Sie Text aus gescannten Dokumenten in mehreren Sprachen sofort.',
      'onboard_title_3': 'Organisieren & Teilen',
      'onboard_desc_3':
          'Konvertieren Sie Scans in PDF, organisieren Sie Dateien und teilen Sie diese sicher.',
      'skip': 'ÜBERSPRINGEN',
      'start': 'STARTEN',
      'home': 'Start',
      'files': 'Dateien',
      'tools': 'Werkzeuge',
      'ocr': 'OCR',
      'profile': 'Profil',
      'scan_doc': 'Dokument scannen',
      'scan_subtitle': 'Belege und Notizen erfassen',
      'quick_actions': 'Schnellaktionen',
      'recent_files': 'Aktuelle Dateien',
      'see_all': 'Alle ansehen',
      'see_all_tools': 'Alle Werkzeuge ansehen',
      'image_to_pdf': 'Bild zu PDF',
      'image_to_text': 'Bild zu Text',
      'pdf_to_text': 'PDF zu Text',
      'pdf_to_image': 'PDF zu Bild',
      'text_to_pdf': 'Text zu PDF',
      'settings': 'Einstellungen',
      'basic': 'Basis',
      'scan': 'Scannen',
      'pdf_ocr_section': 'PDF & OCR',
      'data': 'Daten',
      'theme': 'Design',
      'language': 'Sprache',
      'auto_enhance': 'Auto-Verbesserung',
      'scan_quality': 'Scan-Qualität',
      'default_page_size': 'Seitengröße',
      'ocr_language': 'OCR-Sprache',
      'clear_cache': 'Cache leeren',
      'confirm': 'Bestätigen',
      'cancel': 'Abbrechen',
      'upgrade_title': 'Kostenloser Nutzer',
      'upgrade_subtitle': 'Alle Funktionen freischalten',
      'upgrade_button': 'Upgrade',
      'refer_friend': 'Freunde werben',
      'scan_section': 'Scan-Einstellungen',
      'support_privacy': 'Support & Datenschutz',
      'privacy_policy': 'Datenschutzerklärung',
      'feature_request': 'Feature-Anfrage',
      'report_bug': 'Fehler melden',
      'support_developer': 'Entwickler unterstützen',
      'loading_support_ad': 'Werbung wird geladen...',
      'thank_you_support': 'Vielen Dank für deine Unterstützung!',
      'ad_not_ready':
          'Werbung ist noch nicht bereit. Bitte später erneut versuchen.',
      'data_section': 'Datenverwaltung',
      'use_system_font': 'System-Schriftart',
      'system_font': 'System',
      'app_font': 'App-Schriftart (SamsungOne)',
      'saved_to_downloads': 'Im Downloads-Ordner gespeichert',
      'could_not_save_permission':
          'Speichern nicht möglich: Speicherberechtigung erteilen.',
      'could_not_open_file': 'Datei konnte nicht geöffnet werden.',
      'error_opening_file': 'Beim Öffnen der Datei ist ein Fehler aufgetreten.',
      'scan_error':
          'Beim Scannen ist ein Fehler aufgetreten. Bitte erneut versuchen.',
      'pdf_created_successfully': 'PDF erfolgreich erstellt',
      'image_to_pdf_success': 'Bild zu PDF erfolgreich erstellt',
      'pdfs_merged_success': 'PDFs erfolgreich zusammengeführt',
      'pdf_split_success': 'PDF erfolgreich aufgeteilt',
      'pdf_compressed_success': 'PDF erfolgreich komprimiert',
      'pdf_rotated_success': 'PDF erfolgreich gedreht',
      'pdf_locked_success': 'PDF erfolgreich gesperrt',
      'pdf_unlocked_success': 'PDF erfolgreich entsperrt',
      'incorrect_password': 'Falsches Passwort. Bitte erneut versuchen.',
      'failed_to_unlock': 'PDF konnte nicht entsperrt werden. Bitte erneut versuchen.',
      'pdf_to_image_success': 'PDF zu Bild erfolgreich',
      'pdf_to_text_success': 'PDF zu Text erfolgreich',
      'signature_saved': 'Unterschrift erfolgreich gespeichert',
      'text_to_pdf_error': 'Text konnte nicht in PDF konvertiert werden. Bitte erneut versuchen.',
      'error_prefix':
          'Ein unerwarteter Fehler ist aufgetreten. Bitte erneut versuchen.',
      'pdf_saved_successfully': 'PDF erfolgreich gespeichert',
      'document_saved_successfully': 'Dokument erfolgreich gespeichert',
      'error_saving_doc':
          'Dokument konnte nicht gespeichert werden. Speicherberechtigung prüfen.',
      'error_sharing':
          'Dokument konnte nicht geteilt werden. Bitte erneut versuchen.',
      'text_copied': 'Text in die Zwischenablage kopiert',
      'saved_success_text': 'Erfolgreich als Textdatei gespeichert.',
      'error_picking_image':
          'Bild konnte nicht ausgewählt werden. Bitte erneut versuchen.',
      'error_picking_pdf':
          'PDF konnte nicht geöffnet werden. Bitte erneut versuchen.',
      'error_capturing_image':
          'Foto konnte nicht aufgenommen werden. Kamera prüfen.',
      'cache_cleared': 'Cache geleert',
      'images_saved': 'Bild(er) erfolgreich gespeichert',
      'invalid_page_range': 'Ungültiger Seitenbereich',
      'already_protected': 'Diese PDF ist bereits passwortgeschützt.',
      'not_protected': 'Diese PDF ist nicht passwortgeschützt.',
      'could_not_open_privacy_policy':
          'Datenschutzerklärung konnte nicht geöffnet werden',
      'could_not_open_email': 'E-Mail-App konnte nicht geöffnet werden',
      'deleted_successfully': '\$fileType erfolgreich gelöscht',
      'no_text_in_pdf': 'Kein Text im PDF gefunden',
      'no_text_in_image': 'Kein Text im Bild gefunden',
      'clear': 'Leeren',
      'menu': 'Menü',
      'about': 'Über',
      'about_description': 'RMScanner AI ist eine kostenlose All-in-One-Dokument-Scanner-App mit OCR, PDF-Tools und QR-Scanner. Scannen, konvertieren und teilen Sie Ihre Dokumente jederzeit und überall.',
      'app_version': 'Version',
      'developed_by': 'Entwickelt von',
      'features': 'Funktionen',
      'contact_support': 'Support kontaktieren',
      'convert_photos': 'Fotos konvertieren',
      'extract_ocr': 'Extrahieren (OCR)',
      'convert_pdf': 'PDF konvertieren',
      'create_doc': 'Dok erstellen',
      'no_recent_files': 'Keine aktuellen Dateien',
      'sort_by': 'Sortieren nach',
      'sort_date': 'Datum (Neueste zuerst)',
      'sort_name': 'Name (A-Z)',
      'sort_size': 'Größe (Größte zuerst)',
      'search_hint': 'Dokumente, PDFs suchen...',
      'tab_recent': 'Aktuell',
      'tab_pdfs': 'PDFs',
      'tab_images': 'Bilder',
      'tab_ocr_text': 'OCR-Text',
      'no_files_found': 'Keine Dateien gefunden',
      'just_now': 'Gerade eben',
      'min_ago': 'Min',
      'hours_ago': 'Std',
      'yesterday': 'Gestern',
      'days_ago': 'Tage',
      'all_tools': 'Alle Werkzeuge',
      'pdf_tools': 'PDF-Werkzeuge',
      'converters': 'Konverter',
      'privacy_security': 'Datenschutz & Sicherheit',
      'merge_pdf': 'PDF zusammenführen',
      'split_pdf': 'PDF teilen',
      'compress_pdf': 'PDF komprimieren',
      'rotate_pdf': 'PDF drehen',
      'high_quality': 'HOHE QUALITÄT',
      'fast_scan': 'SCHNELLER SCAN',
      'easy_edit': 'EINFACHE BEARBEITUNG',
      'extract_data': 'DATEN EXTRAHIEREN',
      'lock_pdf': 'PDF sperren',
      'add_password_protection': 'Passwortschutz hinzufügen',
      'unlock_pdf': 'PDF entsperren',
      'remove_restrictions': 'Dokumentbeschränkungen entfernen',
      'add_signature': 'Signatur hinzufügen',
      'digitally_sign': 'Dokumente digital signieren',
      'select_ocr_language': 'OCR-Sprache wählen',
      'extract_text_title': 'Text mit KI extrahieren',
      'extract_text_subtitle': 'Wählen Sie eine Quelle, um Text aus Ihren Dokumenten zu extrahieren.',
      'source_image': 'Bild',
      'source_pdf': 'PDF',
      'source_camera': 'Kamera',
      'capture_document': 'Dokument erfassen',
      'select_file': 'Datei auswählen',
      'extracting_from_image': 'Text aus Bild wird extrahiert...',
      'extracting_from_pdf': 'Text aus PDF wird extrahiert...',
      'extracting_from_capture': 'Text aus Erfassung wird extrahiert...',
      'text_extracted_success': 'Text erfolgreich extrahiert!',
      'extraction_results': 'Extraktionsergebnisse',
      'copy': 'Kopieren',
      'document_statistics': 'Dokumentstatistik',
      'words': 'Wörter',
      'characters': 'Zeichen',
      'extracted_text': 'Extrahierter Text',
      'no_text_hint': 'Kein Text extrahiert. Hier bearbeiten...',
      'save_document': 'Dokument speichern',
      'save': 'Speichern',
      'share': 'Teilen',
      'scan_result': 'Scan-Ergebnis',
      'failed_to_load_image': 'Bild konnte nicht geladen werden',
      'pages_scanned_format': 'gescannt  •  Format wählen',
      'save_as': 'Speichern unter',
      'document': 'Dokument',
      'share_scanned_pages': 'Gescannte Seiten teilen',
      'saving': 'Speichern...',
      'open_settings': 'Einstellungen öffnen',
      'camera_permission_msg': 'Kameraberechtigung ist zum Scannen erforderlich.',
      'permission_required': '\$name-Berechtigung erforderlich',
      'creating_pdf': 'PDF wird erstellt...',
      'delete_confirm': 'Löschen',
      'file_options': 'Dateioptionen',
      'rename': 'Umbenennen',
      'download': 'Herunterladen',
      'delete_confirmation': 'Sind Sie sicher, dass Sie "\$fileName" löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
      'watermark_pdf': 'PDF Wasserzeichen',
      'add_text_watermark': 'Textwasserzeichen zum PDF hinzufügen',
      'watermark_text': 'Wasserzeichentext',
      'watermark_text_hint': 'Wasserzeichentext eingeben...',
      'watermark_opacity': 'Deckkraft',
      'watermark_font_size': 'Schriftgröße',
      'watermark_bold': 'Fett',
      'watermark_italic': 'Kursiv',
      'watermark_tiled': 'Gekachelt (Wiederholungsmuster)',
      'watermark_font': 'Schriftfamilie',
      'watermark_rotation': 'Drehung',
      'watermark_success': 'Wasserzeichen erfolgreich hinzugefügt',
      'watermark_error': 'Wasserzeichen konnte nicht hinzugefügt werden',
      'watermark_text_empty': 'Bitte Wasserzeichentext eingeben',
      'reorder_pages': 'PDF-Seiten anordnen',
      'reorder_delete_pages': 'PDF-Seiten neu anordnen oder löschen',
      'delete_page': 'Löschen',
      'move_up': 'Nach oben',
      'move_down': 'Nach unten',
      'page': 'Seite',
      'reorder_success': 'Seiten erfolgreich neu angeordnet',
      'reorder_error': 'Neuanordnung der Seiten fehlgeschlagen',
      'no_pages_to_show': 'Keine Seiten anzuzeigen',
      'qr_scanner': 'QR-Scanner',
      'scan_qr_barcode': 'QR- & Barcode scannen',
      'qr_code_detected': 'Code erkannt',
      'qr_result': 'Scan-Ergebnis',
      'qr_save_as_text': 'Als Text speichern',
      'qr_save_as_image': 'Als Bild speichern',
      'qr_open_url': 'URL öffnen',
      'qr_copy_text': 'Text kopieren',
      'qr_no_code_detected': 'Noch kein Code erkannt',
      'qr_point_at_code': 'Richten Sie Ihre Kamera auf einen QR-Code oder Barcode',
      'qr_saved_success': 'QR-Code erfolgreich gespeichert',
      'qr_invalid_url': 'Ungültige URL',
      'qr_scan_again': 'Erneut scannen',
      'qr_copied_to_clipboard': 'In die Zwischenablage kopiert',
      'close': 'Schließen',
      'batch_ocr': 'Stapel-OCR',
      'batch_ocr_subtitle': 'Text aus mehreren Bildern extrahieren',
      'batch_ocr_select_images': 'Mehrere Bilder auswählen',
      'batch_ocr_processing': 'Bild wird verarbeitet',
      'batch_ocr_of': 'von',
      'batch_ocr_export_txt': 'Als TXT exportieren',
      'batch_ocr_export_csv': 'Als CSV exportieren',
      'batch_ocr_success': 'Stapel-OCR erfolgreich',
      'batch_ocr_error': 'Stapel-OCR fehlgeschlagen',
      'batch_ocr_no_text': 'In keinem Bild Text gefunden',
      'batch_ocr_select_source': 'Bildquelle für Stapel-OCR wählen',
      'batch_ocr_from_gallery': 'Aus Galerie',
      'batch_ocr_from_camera': 'Aus Kamera',
      'batch_ocr_captured_count': '\$count Bild(er) aufgenommen. Mehr aufnehmen?',
      'batch_ocr_capture_more': 'Mehr aufnehmen',
      'batch_ocr_done': 'Fertig',
      'batch_ocr_results': 'Stapel-OCR Ergebnisse',
      'export_format': 'Exportformat',
      'ai_prompt': 'KI-Prompt',
      'generate_ai_prompt': 'KI-Prompt generieren',
      'ai_prompt_guide': 'So verwenden Sie es mit KI',
      'ai_prompt_guide_step1': '1. Kopieren oder teilen Sie den generierten Prompt',
      'ai_prompt_guide_step2': '2. Öffnen Sie Ihre bevorzugte KI-App (ChatGPT, Gemini, Claude usw.)',
      'ai_prompt_guide_step3': '3. Fügen Sie den Prompt ein und senden Sie ihn an die KI',
      'prompt_summarize': 'Zusammenfassen',
      'prompt_qa': 'F&A',
      'prompt_translate': 'Übersetzen',
      'prompt_extract_data': 'Daten Extrahieren',
      'prompt_summarize_desc': 'Erhalten Sie eine prägnante Zusammenfassung des Dokuments',
      'prompt_qa_desc': 'Stellen Sie Fragen zum Dokument',
      'prompt_translate_desc': 'Übersetzen Sie das Dokument ins Englische',
      'prompt_extract_data_desc': 'Extrahieren Sie Namen, Daten, Beträge und Schlüsselinfo',
      'prompt_copied': 'Prompt in die Zwischenablage kopiert',
      'copy_prompt': 'Prompt Kopieren',
      'share_prompt': 'Prompt Teilen',
      'ai_guide_title': 'KI-Assistent Handbuch',
      'ai_guide_desc': 'Verwenden Sie den generierten Prompt mit Ihrem bevorzugten KI-Tool',
      'open_chatgpt': 'ChatGPT öffnen',
      'open_gemini': 'Gemini öffnen',
      'open_claude': 'Claude öffnen',
      'open_copilot': 'Copilot öffnen',
      'open_deepseek': 'DeepSeek öffnen',
      'prompt_preview': 'Prompt-Vorschau',
      'select_template': 'Vorlage Auswählen',
      'ai_tools': 'KI-Tools',
      'processing': 'Verarbeitung...',
      'may_take_a_while': 'Dies kann bei großen Dateien eine Weile dauern.',
      'notify_when_ready': 'Benachrichtigen wenn fertig',
      'save_as_copy': 'Als Kopie speichern',
      'watermark_preview': 'Vorschau',
      'watermark_apply': 'Wasserzeichen anwenden',
      'open_perplexity': 'Perplexity öffnen',
      'open_mistral': 'Mistral öffnen',
      'open_grok': 'Grok öffnen',
      'open_meta_ai': 'Meta AI öffnen',
      'open_you_com': 'You.com öffnen',
      'open_pi': 'Pi öffnen',
      'open_ai_failed': 'KI-App konnte nicht geöffnet werden. Bitte erneut versuchen.',
      'draw_signature': 'Unterschrift zeichnen',
      'please_sign': 'Bitte unterschreiben Sie im weißen Feld unten.',
      'undo': 'Rückgängig',
      'page_of': 'Seite \$current von \$total',
      'drag_scale_signature': 'Unterschrift ziehen & skalieren',
      'confirm_save_stamp': 'Bestätigen & Stempel speichern',
      'theme_light': 'Hell',
      'theme_dark': 'Dunkel',
      'theme_system': 'System',
      'quality_low': 'Niedrig',
      'quality_medium': 'Mittel',
      'quality_high': 'Hoch',
      'quality_ultra': 'Ultra',
      'clear_cache_confirm': 'Dies löscht alle zwischengespeicherten Dateien (\$size). Fortfahren?',
    },
    'ar': {
      'title': 'RMScanner AI',
      'onboard_title_1': 'امسح من أي مكان',
      'onboard_desc_1':
          'امسح المستندات بسهولة أثناء التنقل بجودة عالية واكتشاف تلقائي للحواف.',
      'onboard_title_2': 'OCR ذكي',
      'onboard_desc_2':
          'استخرج النص من مستنداتك الممسوحة ضوئيًا بلغات متعددة فورًا.',
      'onboard_title_3': 'تنظيم ومشاركة',
      'onboard_desc_3': 'حوّل المسحات إلى PDF، ونظّم الملفات، وشاركها بأمان.',
      'skip': 'تخطي',
      'start': 'ابدأ',
      'home': 'الرئيسية',
      'files': 'الملفات',
      'tools': 'الأدوات',
      'ocr': 'OCR',
      'profile': 'الملف الشخصي',
      'scan_doc': 'مسح المستند',
      'scan_subtitle': 'التقاط الإيصالات والملاحظات',
      'quick_actions': 'إجراءات سريعة',
      'recent_files': 'الملفات الأخيرة',
      'see_all': 'عرض الكل',
      'see_all_tools': 'عرض جميع الأدوات',
      'image_to_pdf': 'صورة إلى PDF',
      'image_to_text': 'صورة إلى نص',
      'pdf_to_text': 'PDF إلى نص',
      'pdf_to_image': 'PDF إلى صورة',
      'text_to_pdf': 'نص إلى PDF',
      'settings': 'الإعدادات',
      'basic': 'أساسي',
      'scan': 'مسح',
      'pdf_ocr_section': 'PDF و OCR',
      'data': 'بيانات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'auto_enhance': 'تحسين تلقائي',
      'scan_quality': 'جودة المسح',
      'default_page_size': 'حجم الصفحة',
      'ocr_language': 'لغة OCR',
      'clear_cache': 'مسح التخزين المؤقت',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'upgrade_title': 'مستخدم مجاني',
      'upgrade_subtitle': 'ترقية لفتح الميزات',
      'upgrade_button': 'ترقية',
      'refer_friend': 'رشح صديقاً',
      'scan_section': 'تفضيلات المسح',
      'support_privacy': 'الدعم والخصوصية',
      'privacy_policy': 'سياسة الخصوصية',
      'feature_request': 'طلب ميزة',
      'report_bug': 'الإبلاغ عن خلل',
      'support_developer': 'دعم المطور',
      'loading_support_ad': 'جاري تحميل الإعلان...',
      'thank_you_support': 'شكراً لدعمكم!',
      'ad_not_ready': 'الإعلان غير جاهز بعد. يرجى المحاولة لاحقاً.',
      'data_section': 'إدارة البيانات',
      'use_system_font': 'خط النظام',
      'system_font': 'النظام',
      'app_font': 'خط التطبيق (SamsungOne)',
      'saved_to_downloads': 'تم الحفظ في مجلد التنزيلات',
      'could_not_save_permission': 'تعذر الحفظ: يرجى السماح بإذن التخزين.',
      'could_not_open_file': 'تعذر فتح الملف.',
      'error_opening_file': 'حدث خطأ أثناء فتح الملف.',
      'scan_error': 'حدث خطأ أثناء المسح. يرجى المحاولة مرة أخرى.',
      'pdf_created_successfully': 'تم إنشاء PDF بنجاح',
      'image_to_pdf_success': 'تم إنشاء PDF من الصورة بنجاح',
      'pdfs_merged_success': 'تم دمج ملفات PDF بنجاح',
      'pdf_split_success': 'تم تقسيم PDF بنجاح',
      'pdf_compressed_success': 'تم ضغط PDF بنجاح',
      'pdf_rotated_success': 'تم تدوير PDF بنجاح',
      'pdf_locked_success': 'تم قفل PDF بنجاح',
      'pdf_unlocked_success': 'تم إلغاء قفل PDF بنجاح',
      'incorrect_password': 'كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.',
      'failed_to_unlock': 'فشل إلغاء قفل PDF. يرجى المحاولة مرة أخرى.',
      'pdf_to_image_success': 'تم تحويل PDF إلى صورة بنجاح',
      'pdf_to_text_success': 'تم تحويل PDF إلى نص بنجاح',
      'signature_saved': 'تم حفظ التوقيع بنجاح',
      'text_to_pdf_error': 'فشل تحويل النص إلى PDF. يرجى المحاولة مرة أخرى.',
      'error_prefix': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
      'pdf_saved_successfully': 'تم حفظ PDF بنجاح',
      'document_saved_successfully': 'تم حفظ المستند بنجاح',
      'error_saving_doc': 'فشل حفظ المستند. تحقق من أذونات التخزين.',
      'error_sharing': 'تعذر مشاركة المستند. يرجى المحاولة مرة أخرى.',
      'text_copied': 'تم نسخ النص إلى الحافظة',
      'saved_success_text': 'تم الحفظ بنجاح كملف نصي.',
      'error_picking_image': 'تعذر اختيار الصورة. يرجى المحاولة مرة أخرى.',
      'error_picking_pdf': 'تعذر فتح PDF. يرجى المحاولة مرة أخرى.',
      'error_capturing_image': 'تعذر التقاط الصورة. تحقق من الكاميرا.',
      'cache_cleared': 'تم مسح التخزين المؤقت',
      'images_saved': 'تم حفظ الصورة بنجاح',
      'invalid_page_range': 'نطاق الصفحات غير صالح',
      'already_protected': 'ملف PDF محمي بكلمة مرور بالفعل.',
      'not_protected': 'ملف PDF غير محمي بكلمة مرور.',
      'could_not_open_privacy_policy': 'تعذر فتح سياسة الخصوصية',
      'could_not_open_email': 'تعذر فتح تطبيق البريد الإلكتروني',
      'deleted_successfully': 'تم حذف \$fileType بنجاح',
      'no_text_in_pdf': 'لم يتم العثور على نص في PDF',
      'no_text_in_image': 'لم يتم العثور على نص في الصورة',
      'clear': 'مسح',
      'menu': 'القائمة',
      'about': 'حول',
      'about_description': 'RMScanner AI هو تطبيق مجاني لمسح المستندات شامل مع OCR وأدوات PDF وماسح QR. امسح وحول وشارك مستنداتك في أي وقت وفي أي مكان.',
      'app_version': 'الإصدار',
      'developed_by': 'تم التطوير بواسطة',
      'features': 'الميزات',
      'contact_support': 'تواصل مع الدعم',
      'convert_photos': 'تحويل الصور',
      'extract_ocr': 'استخراج (OCR)',
      'convert_pdf': 'تحويل PDF',
      'create_doc': 'إنشاء مستند',
      'no_recent_files': 'لا توجد ملفات حديثة',
      'sort_by': 'فرز حسب',
      'sort_date': 'التاريخ (الأحدث أولاً)',
      'sort_name': 'الاسم (A-Z)',
      'sort_size': 'الحجم (الأكبر أولاً)',
      'search_hint': 'البحث في المستندات، PDF...',
      'tab_recent': 'الأحدث',
      'tab_pdfs': 'PDF',
      'tab_images': 'الصور',
      'tab_ocr_text': 'نص OCR',
      'no_files_found': 'لم يتم العثور على ملفات',
      'just_now': 'الآن',
      'min_ago': 'دقيقة',
      'hours_ago': 'ساعة',
      'yesterday': 'أمس',
      'days_ago': 'أيام',
      'all_tools': 'جميع الأدوات',
      'pdf_tools': 'أدوات PDF',
      'converters': 'المحولات',
      'privacy_security': 'الخصوصية والأمان',
      'merge_pdf': 'دمج PDF',
      'split_pdf': 'تقسيم PDF',
      'compress_pdf': 'ضغط PDF',
      'rotate_pdf': 'تدوير PDF',
      'high_quality': 'جودة عالية',
      'fast_scan': 'مسح سريع',
      'easy_edit': 'تحرير سهل',
      'extract_data': 'استخراج البيانات',
      'lock_pdf': 'قفل PDF',
      'add_password_protection': 'إضافة حماية بكلمة مرور',
      'unlock_pdf': 'فتح PDF',
      'remove_restrictions': 'إزالة قيود المستند',
      'add_signature': 'إضافة توقيع',
      'digitally_sign': 'توقيع المستندات رقمياً',
      'select_ocr_language': 'اختر لغة OCR',
      'extract_text_title': 'استخراج النص بالذكاء الاصطناعي',
      'extract_text_subtitle': 'اختر مصدراً لبدء استخراج النص من مستنداتك.',
      'source_image': 'صورة',
      'source_pdf': 'PDF',
      'source_camera': 'كاميرا',
      'capture_document': 'التقاط مستند',
      'select_file': 'اختر ملف',
      'extracting_from_image': 'جاري استخراج النص من الصورة...',
      'extracting_from_pdf': 'جاري استخراج النص من PDF...',
      'extracting_from_capture': 'جاري استخراج النص من الالتقاط...',
      'text_extracted_success': 'تم استخراج النص بنجاح!',
      'extraction_results': 'نتائج الاستخراج',
      'copy': 'نسخ',
      'document_statistics': 'إحصائيات المستند',
      'words': 'كلمات',
      'characters': 'أحرف',
      'extracted_text': 'النص المستخرج',
      'no_text_hint': 'لم يتم استخراج نص. حاول التحرير هنا...',
      'save_document': 'حفظ المستند',
      'save': 'حفظ',
      'share': 'مشاركة',
      'scan_result': 'نتيجة المسح',
      'failed_to_load_image': 'فشل تحميل الصورة',
      'pages_scanned_format': 'ممسوحة  •  اختر تنسيق الحفظ',
      'save_as': 'حفظ باسم',
      'document': 'مستند',
      'share_scanned_pages': 'مشاركة الصفحات الممسوحة',
      'saving': 'جاري الحفظ...',
      'open_settings': 'فتح الإعدادات',
      'camera_permission_msg': 'إذن الكاميرا مطلوب للمسح.',
      'permission_required': 'إذن \$name مطلوب',
      'creating_pdf': 'جاري إنشاء PDF...',
      'delete_confirm': 'حذف',
      'file_options': 'خيارات الملف',
      'rename': 'إعادة تسمية',
      'download': 'تنزيل',
      'delete_confirmation': 'هل أنت متأكد من حذف "\$fileName"؟ لا يمكن التراجع عن هذا الإجراء.',
      'watermark_pdf': 'علامة مائية PDF',
      'add_text_watermark': 'إضافة علامة مائية نصية إلى PDF',
      'watermark_text': 'نص العلامة المائية',
      'watermark_text_hint': 'أدخل نص العلامة المائية...',
      'watermark_opacity': 'الشفافية',
      'watermark_font_size': 'حجم الخط',
      'watermark_bold': 'غامق',
      'watermark_italic': 'مائل',
      'watermark_tiled': 'متكرر (نمط مكرر)',
      'watermark_font': 'عائلة الخط',
      'watermark_rotation': 'الدوران',
      'watermark_success': 'تمت إضافة العلامة المائية بنجاح',
      'watermark_error': 'فشل في إضافة العلامة المائية',
      'watermark_text_empty': 'يرجى إدخال نص العلامة المائية',
      'reorder_pages': 'ترتيب صفحات PDF',
      'reorder_delete_pages': 'إعادة ترتيب أو حذف صفحات PDF',
      'delete_page': 'حذف',
      'move_up': 'تحريك لأعلى',
      'move_down': 'تحريك لأسفل',
      'page': 'صفحة',
      'reorder_success': 'تمت إعادة ترتيب الصفحات بنجاح',
      'reorder_error': 'فشل في إعادة ترتيب الصفحات',
      'no_pages_to_show': 'لا توجد صفحات للعرض',
      'qr_scanner': 'ماسح QR',
      'scan_qr_barcode': 'مسح QR والباركود',
      'qr_code_detected': 'تم اكتشاف الرمز',
      'qr_result': 'نتيجة المسح',
      'qr_save_as_text': 'حفظ كنص',
      'qr_save_as_image': 'حفظ كصورة',
      'qr_open_url': 'فتح الرابط',
      'qr_copy_text': 'نسخ النص',
      'qr_no_code_detected': 'لم يتم اكتشاف أي رمز بعد',
      'qr_point_at_code': 'وجه كاميرتك نحو رمز QR أو باركود',
      'qr_saved_success': 'تم حفظ رمز QR بنجاح',
      'qr_invalid_url': 'رابط غير صالح',
      'qr_scan_again': 'مسح مرة أخرى',
      'qr_copied_to_clipboard': 'تم النسخ إلى الحافظة',
      'close': 'إغلاق',
      'batch_ocr': 'OCR دفعي',
      'batch_ocr_subtitle': 'استخراج النص من صور متعددة',
      'batch_ocr_select_images': 'تحديد صور متعددة',
      'batch_ocr_processing': 'معالجة الصورة',
      'batch_ocr_of': 'من',
      'batch_ocr_export_txt': 'تصدير كـ TXT',
      'batch_ocr_export_csv': 'تصدير كـ CSV',
      'batch_ocr_success': 'OCR الدفعي ناجح',
      'batch_ocr_error': 'فشل OCR الدفعي',
      'batch_ocr_no_text': 'لم يتم العثور على نص في أي صورة',
      'batch_ocr_select_source': 'اختر مصدر الصور لـ OCR الدفعي',
      'batch_ocr_from_gallery': 'من المعرض',
      'batch_ocr_from_camera': 'من الكاميرا',
      'batch_ocr_captured_count': 'تم التقاط \$count صورة. التقاط المزيد؟',
      'batch_ocr_capture_more': 'التقاط المزيد',
      'batch_ocr_done': 'تم',
      'batch_ocr_results': 'نتائج OCR الدفعي',
      'export_format': 'تنسيق التصدير',
      'ai_prompt': 'موجه الذكاء الاصطناعي',
      'generate_ai_prompt': 'إنشاء موجه ذكاء اصطناعي',
      'ai_prompt_guide': 'كيفية الاستخدام مع الذكاء الاصطناعي',
      'ai_prompt_guide_step1': '1. انسخ أو شارك الموجه المُنشأ',
      'ai_prompt_guide_step2': '2. افتح تطبيق الذكاء الاصطناعي المفضل لديك (ChatGPT, Gemini, Claude, إلخ)',
      'ai_prompt_guide_step3': '3. الصق الموجه وأرسله إلى الذكاء الاصطناعي',
      'prompt_summarize': 'تلخيص',
      'prompt_qa': 'أسئلة وأجوبة',
      'prompt_translate': 'ترجمة',
      'prompt_extract_data': 'استخراج البيانات',
      'prompt_summarize_desc': 'احصل على ملخص موجز للمستند',
      'prompt_qa_desc': 'اطرح أسئلة حول المستند',
      'prompt_translate_desc': 'ترجم المستند إلى الإنجليزية',
      'prompt_extract_data_desc': 'استخرج الأسماء والتواريخ والمبالغ والمعلومات الرئيسية',
      'prompt_copied': 'تم نسخ الموجه إلى الحافظة',
      'copy_prompt': 'نسخ الموجه',
      'share_prompt': 'مشاركة الموجه',
      'ai_guide_title': 'دليل مساعد الذكاء الاصطناعي',
      'ai_guide_desc': 'استخدم الموجه المُنشأ مع أداة الذكاء الاصطناعي المفضلة لديك',
      'open_chatgpt': 'فتح ChatGPT',
      'open_gemini': 'فتح Gemini',
      'open_claude': 'فتح Claude',
      'open_copilot': 'فتح Copilot',
      'open_deepseek': 'فتح DeepSeek',
      'prompt_preview': 'معاينة الموجه',
      'select_template': 'اختر قالباً',
      'ai_tools': 'أدوات الذكاء الاصطناعي',
      'processing': 'جاري المعالجة...',
      'may_take_a_while': 'قد يستغرق هذا بعض الوقت للملفات الكبيرة.',
      'notify_when_ready': 'إعلام عند الانتهاء',
      'save_as_copy': 'حفظ كنسخة',
      'watermark_preview': 'معاينة',
      'watermark_apply': 'تطبيق العلامة المائية',
      'open_perplexity': 'فتح Perplexity',
      'open_mistral': 'فتح Mistral',
      'open_grok': 'فتح Grok',
      'open_meta_ai': 'فتح Meta AI',
      'open_you_com': 'فتح You.com',
      'open_pi': 'فتح Pi',
      'open_ai_failed': 'تعذر فتح تطبيق الذكاء الاصطناعي. يرجى المحاولة مرة أخرى.',
      'draw_signature': 'رسم التوقيع',
      'please_sign': 'يرجى التوقيع داخل المربع الأبيض أدناه.',
      'undo': 'تراجع',
      'page_of': 'صفحة \$current من \$total',
      'drag_scale_signature': 'اسحب وقيّم التوقيع',
      'confirm_save_stamp': 'تأكيد وحفظ الختم',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'theme_system': 'النظام',
      'quality_low': 'منخفض',
      'quality_medium': 'متوسط',
      'quality_high': 'عالي',
      'quality_ultra': 'فائق',
      'clear_cache_confirm': 'سيؤدي هذا إلى حذف جميع الملفات المخزنة مؤقتًا (\$size). هل تريد المتابعة؟',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String tr(String key) => translate(key);
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) {
    return [
      'en',
      'id',
      'bn',
      'hi',
      'fr',
      'de',
      'ar',
    ].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
